package com.p2g.mybatis.dao.sys;

import com.p2g.mybatis.model.sys.ViewRolePermission;
import java.util.List;

public interface ViewRolePermissionMapper {


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table view_role_permission
     *
     * @mbggenerated
     */
    List<ViewRolePermission> selectAll();
}