package com.shop.mybatis.dao.generator;

import com.shop.mybatis.model.generator.Orderform;
import java.util.List;

public interface OrderformMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderform
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderform
     *
     * @mbggenerated
     */
    int insert(Orderform record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderform
     *
     * @mbggenerated
     */
    Orderform selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderform
     *
     * @mbggenerated
     */
    List<Orderform> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderform
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Orderform record);
}