package com.shop.mybatis.dao.generator;

import com.shop.mybatis.model.generator.Prize;
import java.util.List;

public interface PrizeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prize
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prize
     *
     * @mbggenerated
     */
    int insert(Prize record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prize
     *
     * @mbggenerated
     */
    Prize selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prize
     *
     * @mbggenerated
     */
    List<Prize> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prize
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Prize record);
}