package com.shop.mybatis.model.generator;

import java.io.Serializable;
import java.util.Date;

public class Prizeconfig implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prizeconfig.prize_id
     *
     * @mbggenerated
     */
    private Long prizeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prizeconfig.top_Level
     *
     * @mbggenerated
     */
    private Long topLevel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prizeconfig.sequence
     *
     * @mbggenerated
     */
    private String sequence;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prizeconfig.sort
     *
     * @mbggenerated
     */
    private String sort;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prizeconfig.prize_name
     *
     * @mbggenerated
     */
    private String prizeName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prizeconfig.probability
     *
     * @mbggenerated
     */
    private Integer probability;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prizeconfig.update_time
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prizeconfig.stock_num
     *
     * @mbggenerated
     */
    private Integer stockNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table prizeconfig
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prizeconfig.prize_id
     *
     * @return the value of prizeconfig.prize_id
     *
     * @mbggenerated
     */
    public Long getPrizeId() {
        return prizeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prizeconfig.prize_id
     *
     * @param prizeId the value for prizeconfig.prize_id
     *
     * @mbggenerated
     */
    public void setPrizeId(Long prizeId) {
        this.prizeId = prizeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prizeconfig.top_Level
     *
     * @return the value of prizeconfig.top_Level
     *
     * @mbggenerated
     */
    public Long getTopLevel() {
        return topLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prizeconfig.top_Level
     *
     * @param topLevel the value for prizeconfig.top_Level
     *
     * @mbggenerated
     */
    public void setTopLevel(Long topLevel) {
        this.topLevel = topLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prizeconfig.sequence
     *
     * @return the value of prizeconfig.sequence
     *
     * @mbggenerated
     */
    public String getSequence() {
        return sequence;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prizeconfig.sequence
     *
     * @param sequence the value for prizeconfig.sequence
     *
     * @mbggenerated
     */
    public void setSequence(String sequence) {
        this.sequence = sequence == null ? null : sequence.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prizeconfig.sort
     *
     * @return the value of prizeconfig.sort
     *
     * @mbggenerated
     */
    public String getSort() {
        return sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prizeconfig.sort
     *
     * @param sort the value for prizeconfig.sort
     *
     * @mbggenerated
     */
    public void setSort(String sort) {
        this.sort = sort == null ? null : sort.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prizeconfig.prize_name
     *
     * @return the value of prizeconfig.prize_name
     *
     * @mbggenerated
     */
    public String getPrizeName() {
        return prizeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prizeconfig.prize_name
     *
     * @param prizeName the value for prizeconfig.prize_name
     *
     * @mbggenerated
     */
    public void setPrizeName(String prizeName) {
        this.prizeName = prizeName == null ? null : prizeName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prizeconfig.probability
     *
     * @return the value of prizeconfig.probability
     *
     * @mbggenerated
     */
    public Integer getProbability() {
        return probability;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prizeconfig.probability
     *
     * @param probability the value for prizeconfig.probability
     *
     * @mbggenerated
     */
    public void setProbability(Integer probability) {
        this.probability = probability;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prizeconfig.update_time
     *
     * @return the value of prizeconfig.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prizeconfig.update_time
     *
     * @param updateTime the value for prizeconfig.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prizeconfig.stock_num
     *
     * @return the value of prizeconfig.stock_num
     *
     * @mbggenerated
     */
    public Integer getStockNum() {
        return stockNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prizeconfig.stock_num
     *
     * @param stockNum the value for prizeconfig.stock_num
     *
     * @mbggenerated
     */
    public void setStockNum(Integer stockNum) {
        this.stockNum = stockNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prizeconfig
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", prizeId=").append(prizeId);
        sb.append(", topLevel=").append(topLevel);
        sb.append(", sequence=").append(sequence);
        sb.append(", sort=").append(sort);
        sb.append(", prizeName=").append(prizeName);
        sb.append(", probability=").append(probability);
        sb.append(", updateTime=").append(updateTime);
        sb.append(", stockNum=").append(stockNum);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prizeconfig
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Prizeconfig other = (Prizeconfig) that;
        return (this.getPrizeId() == null ? other.getPrizeId() == null : this.getPrizeId().equals(other.getPrizeId()))
            && (this.getTopLevel() == null ? other.getTopLevel() == null : this.getTopLevel().equals(other.getTopLevel()))
            && (this.getSequence() == null ? other.getSequence() == null : this.getSequence().equals(other.getSequence()))
            && (this.getSort() == null ? other.getSort() == null : this.getSort().equals(other.getSort()))
            && (this.getPrizeName() == null ? other.getPrizeName() == null : this.getPrizeName().equals(other.getPrizeName()))
            && (this.getProbability() == null ? other.getProbability() == null : this.getProbability().equals(other.getProbability()))
            && (this.getUpdateTime() == null ? other.getUpdateTime() == null : this.getUpdateTime().equals(other.getUpdateTime()))
            && (this.getStockNum() == null ? other.getStockNum() == null : this.getStockNum().equals(other.getStockNum()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prizeconfig
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getPrizeId() == null) ? 0 : getPrizeId().hashCode());
        result = prime * result + ((getTopLevel() == null) ? 0 : getTopLevel().hashCode());
        result = prime * result + ((getSequence() == null) ? 0 : getSequence().hashCode());
        result = prime * result + ((getSort() == null) ? 0 : getSort().hashCode());
        result = prime * result + ((getPrizeName() == null) ? 0 : getPrizeName().hashCode());
        result = prime * result + ((getProbability() == null) ? 0 : getProbability().hashCode());
        result = prime * result + ((getUpdateTime() == null) ? 0 : getUpdateTime().hashCode());
        result = prime * result + ((getStockNum() == null) ? 0 : getStockNum().hashCode());
        return result;
    }
}