package com.shop.mybatis.dao.generator;

import com.shop.mybatis.model.generator.InviteAuthorityCode;
import com.shop.mybatis.model.generator.InviteAuthorityCodeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface InviteAuthorityCodeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table invite_authority_code
     *
     * @mbggenerated Mon May 21 17:26:34 CST 2018
     */
    int countByExample(InviteAuthorityCodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table invite_authority_code
     *
     * @mbggenerated Mon May 21 17:26:34 CST 2018
     */
    int deleteByExample(InviteAuthorityCodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table invite_authority_code
     *
     * @mbggenerated Mon May 21 17:26:34 CST 2018
     */
    int deleteByPrimaryKey(String inviteCode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table invite_authority_code
     *
     * @mbggenerated Mon May 21 17:26:34 CST 2018
     */
    int insert(InviteAuthorityCode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table invite_authority_code
     *
     * @mbggenerated Mon May 21 17:26:34 CST 2018
     */
    int insertSelective(InviteAuthorityCode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table invite_authority_code
     *
     * @mbggenerated Mon May 21 17:26:34 CST 2018
     */
    List<InviteAuthorityCode> selectByExample(InviteAuthorityCodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table invite_authority_code
     *
     * @mbggenerated Mon May 21 17:26:34 CST 2018
     */
    InviteAuthorityCode selectByPrimaryKey(String inviteCode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table invite_authority_code
     *
     * @mbggenerated Mon May 21 17:26:34 CST 2018
     */
    int updateByExampleSelective(@Param("record") InviteAuthorityCode record, @Param("example") InviteAuthorityCodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table invite_authority_code
     *
     * @mbggenerated Mon May 21 17:26:34 CST 2018
     */
    int updateByExample(@Param("record") InviteAuthorityCode record, @Param("example") InviteAuthorityCodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table invite_authority_code
     *
     * @mbggenerated Mon May 21 17:26:34 CST 2018
     */
    int updateByPrimaryKeySelective(InviteAuthorityCode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table invite_authority_code
     *
     * @mbggenerated Mon May 21 17:26:34 CST 2018
     */
    int updateByPrimaryKey(InviteAuthorityCode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table invite_authority_code
     *
     * @mbggenerated Mon May 21 17:26:34 CST 2018
     */
    List<InviteAuthorityCode> selectByExample(InviteAuthorityCodeExample example, RowBounds rowBounds);

	void insertBatch(List<InviteAuthorityCode> codes);
}