package com.shop.mybatis.dao.generator;

import com.shop.mybatis.model.generator.WxpayRecord;
import com.shop.mybatis.model.generator.WxpayRecordExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface WxpayRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wxpay_record
     *
     * @mbggenerated Mon Jul 30 16:13:59 CST 2018
     */
    int countByExample(WxpayRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wxpay_record
     *
     * @mbggenerated Mon Jul 30 16:13:59 CST 2018
     */
    int deleteByExample(WxpayRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wxpay_record
     *
     * @mbggenerated Mon Jul 30 16:13:59 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wxpay_record
     *
     * @mbggenerated Mon Jul 30 16:13:59 CST 2018
     */
    int insert(WxpayRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wxpay_record
     *
     * @mbggenerated Mon Jul 30 16:13:59 CST 2018
     */
    int insertSelective(WxpayRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wxpay_record
     *
     * @mbggenerated Mon Jul 30 16:13:59 CST 2018
     */
    List<WxpayRecord> selectByExample(WxpayRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wxpay_record
     *
     * @mbggenerated Mon Jul 30 16:13:59 CST 2018
     */
    WxpayRecord selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wxpay_record
     *
     * @mbggenerated Mon Jul 30 16:13:59 CST 2018
     */
    int updateByExampleSelective(@Param("record") WxpayRecord record, @Param("example") WxpayRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wxpay_record
     *
     * @mbggenerated Mon Jul 30 16:13:59 CST 2018
     */
    int updateByExample(@Param("record") WxpayRecord record, @Param("example") WxpayRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wxpay_record
     *
     * @mbggenerated Mon Jul 30 16:13:59 CST 2018
     */
    int updateByPrimaryKeySelective(WxpayRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wxpay_record
     *
     * @mbggenerated Mon Jul 30 16:13:59 CST 2018
     */
    int updateByPrimaryKey(WxpayRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wxpay_record
     *
     * @mbggenerated Mon Jul 30 16:13:59 CST 2018
     */
    List<WxpayRecord> selectByExample(WxpayRecordExample example, RowBounds rowBounds);
}