package com.p2g.mybatis.model.generator;

import java.io.Serializable;
import java.util.Date;

public class AdminLoginLog implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_login_log.admin_login_log_id
     *
     * @mbggenerated
     */
    private Integer adminLoginLogId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_login_log.session_id
     *
     * @mbggenerated
     */
    private String sessionId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_login_log.admin_id
     *
     * @mbggenerated
     */
    private Integer adminId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_login_log.ip
     *
     * @mbggenerated
     */
    private String ip;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_login_log.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_login_log.admin_code
     *
     * @mbggenerated
     */
    private String adminCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table admin_login_log
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin_login_log.admin_login_log_id
     *
     * @return the value of admin_login_log.admin_login_log_id
     *
     * @mbggenerated
     */
    public Integer getAdminLoginLogId() {
        return adminLoginLogId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin_login_log.admin_login_log_id
     *
     * @param adminLoginLogId the value for admin_login_log.admin_login_log_id
     *
     * @mbggenerated
     */
    public void setAdminLoginLogId(Integer adminLoginLogId) {
        this.adminLoginLogId = adminLoginLogId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin_login_log.session_id
     *
     * @return the value of admin_login_log.session_id
     *
     * @mbggenerated
     */
    public String getSessionId() {
        return sessionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin_login_log.session_id
     *
     * @param sessionId the value for admin_login_log.session_id
     *
     * @mbggenerated
     */
    public void setSessionId(String sessionId) {
        this.sessionId = sessionId == null ? null : sessionId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin_login_log.admin_id
     *
     * @return the value of admin_login_log.admin_id
     *
     * @mbggenerated
     */
    public Integer getAdminId() {
        return adminId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin_login_log.admin_id
     *
     * @param adminId the value for admin_login_log.admin_id
     *
     * @mbggenerated
     */
    public void setAdminId(Integer adminId) {
        this.adminId = adminId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin_login_log.ip
     *
     * @return the value of admin_login_log.ip
     *
     * @mbggenerated
     */
    public String getIp() {
        return ip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin_login_log.ip
     *
     * @param ip the value for admin_login_log.ip
     *
     * @mbggenerated
     */
    public void setIp(String ip) {
        this.ip = ip == null ? null : ip.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin_login_log.create_time
     *
     * @return the value of admin_login_log.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin_login_log.create_time
     *
     * @param createTime the value for admin_login_log.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin_login_log.admin_code
     *
     * @return the value of admin_login_log.admin_code
     *
     * @mbggenerated
     */
    public String getAdminCode() {
        return adminCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin_login_log.admin_code
     *
     * @param adminCode the value for admin_login_log.admin_code
     *
     * @mbggenerated
     */
    public void setAdminCode(String adminCode) {
        this.adminCode = adminCode == null ? null : adminCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_login_log
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", adminLoginLogId=").append(adminLoginLogId);
        sb.append(", sessionId=").append(sessionId);
        sb.append(", adminId=").append(adminId);
        sb.append(", ip=").append(ip);
        sb.append(", createTime=").append(createTime);
        sb.append(", adminCode=").append(adminCode);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_login_log
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        AdminLoginLog other = (AdminLoginLog) that;
        return (this.getAdminLoginLogId() == null ? other.getAdminLoginLogId() == null : this.getAdminLoginLogId().equals(other.getAdminLoginLogId()))
            && (this.getSessionId() == null ? other.getSessionId() == null : this.getSessionId().equals(other.getSessionId()))
            && (this.getAdminId() == null ? other.getAdminId() == null : this.getAdminId().equals(other.getAdminId()))
            && (this.getIp() == null ? other.getIp() == null : this.getIp().equals(other.getIp()))
            && (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime().equals(other.getCreateTime()))
            && (this.getAdminCode() == null ? other.getAdminCode() == null : this.getAdminCode().equals(other.getAdminCode()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_login_log
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getAdminLoginLogId() == null) ? 0 : getAdminLoginLogId().hashCode());
        result = prime * result + ((getSessionId() == null) ? 0 : getSessionId().hashCode());
        result = prime * result + ((getAdminId() == null) ? 0 : getAdminId().hashCode());
        result = prime * result + ((getIp() == null) ? 0 : getIp().hashCode());
        result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
        result = prime * result + ((getAdminCode() == null) ? 0 : getAdminCode().hashCode());
        return result;
    }
}