package com.p2g.mybatis.model.generator;

import java.io.Serializable;
import java.util.Date;

public class AdminDoKind implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_do_kind.admin_do_kind_code
     *
     * @mbggenerated
     */
    private String adminDoKindCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_do_kind.admin_do_kind_text
     *
     * @mbggenerated
     */
    private String adminDoKindText;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_do_kind.update_time
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table admin_do_kind
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin_do_kind.admin_do_kind_code
     *
     * @return the value of admin_do_kind.admin_do_kind_code
     *
     * @mbggenerated
     */
    public String getAdminDoKindCode() {
        return adminDoKindCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin_do_kind.admin_do_kind_code
     *
     * @param adminDoKindCode the value for admin_do_kind.admin_do_kind_code
     *
     * @mbggenerated
     */
    public void setAdminDoKindCode(String adminDoKindCode) {
        this.adminDoKindCode = adminDoKindCode == null ? null : adminDoKindCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin_do_kind.admin_do_kind_text
     *
     * @return the value of admin_do_kind.admin_do_kind_text
     *
     * @mbggenerated
     */
    public String getAdminDoKindText() {
        return adminDoKindText;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin_do_kind.admin_do_kind_text
     *
     * @param adminDoKindText the value for admin_do_kind.admin_do_kind_text
     *
     * @mbggenerated
     */
    public void setAdminDoKindText(String adminDoKindText) {
        this.adminDoKindText = adminDoKindText == null ? null : adminDoKindText.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin_do_kind.update_time
     *
     * @return the value of admin_do_kind.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin_do_kind.update_time
     *
     * @param updateTime the value for admin_do_kind.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_do_kind
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", adminDoKindCode=").append(adminDoKindCode);
        sb.append(", adminDoKindText=").append(adminDoKindText);
        sb.append(", updateTime=").append(updateTime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_do_kind
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        AdminDoKind other = (AdminDoKind) that;
        return (this.getAdminDoKindCode() == null ? other.getAdminDoKindCode() == null : this.getAdminDoKindCode().equals(other.getAdminDoKindCode()))
            && (this.getAdminDoKindText() == null ? other.getAdminDoKindText() == null : this.getAdminDoKindText().equals(other.getAdminDoKindText()))
            && (this.getUpdateTime() == null ? other.getUpdateTime() == null : this.getUpdateTime().equals(other.getUpdateTime()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_do_kind
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getAdminDoKindCode() == null) ? 0 : getAdminDoKindCode().hashCode());
        result = prime * result + ((getAdminDoKindText() == null) ? 0 : getAdminDoKindText().hashCode());
        result = prime * result + ((getUpdateTime() == null) ? 0 : getUpdateTime().hashCode());
        return result;
    }
}