package com.p2g.mybatis.model.generator;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class DqBankCheck implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dq_bank_check.deposit_bank_check_id
     *
     * @mbggenerated
     */
    private Long depositBankCheckId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dq_bank_check.user_id
     *
     * @mbggenerated
     */
    private Long userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dq_bank_check.dq_product_id
     *
     * @mbggenerated
     */
    private Long dqProductId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dq_bank_check.dq_trans_log_id
     *
     * @mbggenerated
     */
    private Long dqTransLogId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dq_bank_check.trans_no
     *
     * @mbggenerated
     */
    private String transNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dq_bank_check.invest_amt
     *
     * @mbggenerated
     */
    private BigDecimal investAmt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dq_bank_check.dq_rates
     *
     * @mbggenerated
     */
    private BigDecimal dqRates;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dq_bank_check.active_rates
     *
     * @mbggenerated
     */
    private BigDecimal activeRates;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dq_bank_check.ticket_rates
     *
     * @mbggenerated
     */
    private BigDecimal ticketRates;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dq_bank_check.invest_profit_amt
     *
     * @mbggenerated
     */
    private BigDecimal investProfitAmt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dq_bank_check.active_profit_amt
     *
     * @mbggenerated
     */
    private BigDecimal activeProfitAmt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dq_bank_check.ticket_profit_amt
     *
     * @mbggenerated
     */
    private BigDecimal ticketProfitAmt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dq_bank_check.total_profit_amt
     *
     * @mbggenerated
     */
    private BigDecimal totalProfitAmt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dq_bank_check.total_withdraw_amt
     *
     * @mbggenerated
     */
    private BigDecimal totalWithdrawAmt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dq_bank_check.invest_time
     *
     * @mbggenerated
     */
    private Date investTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dq_bank_check.invest_days
     *
     * @mbggenerated
     */
    private Integer investDays;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dq_bank_check.end_time
     *
     * @mbggenerated
     */
    private Date endTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dq_bank_check.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dq_bank_check.check_status
     *
     * @mbggenerated
     */
    private String checkStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dq_bank_check.check_time
     *
     * @mbggenerated
     */
    private Date checkTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dq_bank_check.pay_status
     *
     * @mbggenerated
     */
    private String payStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dq_bank_check.pay_time
     *
     * @mbggenerated
     */
    private Date payTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table dq_bank_check
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dq_bank_check.deposit_bank_check_id
     *
     * @return the value of dq_bank_check.deposit_bank_check_id
     *
     * @mbggenerated
     */
    public Long getDepositBankCheckId() {
        return depositBankCheckId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dq_bank_check.deposit_bank_check_id
     *
     * @param depositBankCheckId the value for dq_bank_check.deposit_bank_check_id
     *
     * @mbggenerated
     */
    public void setDepositBankCheckId(Long depositBankCheckId) {
        this.depositBankCheckId = depositBankCheckId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dq_bank_check.user_id
     *
     * @return the value of dq_bank_check.user_id
     *
     * @mbggenerated
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dq_bank_check.user_id
     *
     * @param userId the value for dq_bank_check.user_id
     *
     * @mbggenerated
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dq_bank_check.dq_product_id
     *
     * @return the value of dq_bank_check.dq_product_id
     *
     * @mbggenerated
     */
    public Long getDqProductId() {
        return dqProductId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dq_bank_check.dq_product_id
     *
     * @param dqProductId the value for dq_bank_check.dq_product_id
     *
     * @mbggenerated
     */
    public void setDqProductId(Long dqProductId) {
        this.dqProductId = dqProductId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dq_bank_check.dq_trans_log_id
     *
     * @return the value of dq_bank_check.dq_trans_log_id
     *
     * @mbggenerated
     */
    public Long getDqTransLogId() {
        return dqTransLogId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dq_bank_check.dq_trans_log_id
     *
     * @param dqTransLogId the value for dq_bank_check.dq_trans_log_id
     *
     * @mbggenerated
     */
    public void setDqTransLogId(Long dqTransLogId) {
        this.dqTransLogId = dqTransLogId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dq_bank_check.trans_no
     *
     * @return the value of dq_bank_check.trans_no
     *
     * @mbggenerated
     */
    public String getTransNo() {
        return transNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dq_bank_check.trans_no
     *
     * @param transNo the value for dq_bank_check.trans_no
     *
     * @mbggenerated
     */
    public void setTransNo(String transNo) {
        this.transNo = transNo == null ? null : transNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dq_bank_check.invest_amt
     *
     * @return the value of dq_bank_check.invest_amt
     *
     * @mbggenerated
     */
    public BigDecimal getInvestAmt() {
        return investAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dq_bank_check.invest_amt
     *
     * @param investAmt the value for dq_bank_check.invest_amt
     *
     * @mbggenerated
     */
    public void setInvestAmt(BigDecimal investAmt) {
        this.investAmt = investAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dq_bank_check.dq_rates
     *
     * @return the value of dq_bank_check.dq_rates
     *
     * @mbggenerated
     */
    public BigDecimal getDqRates() {
        return dqRates;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dq_bank_check.dq_rates
     *
     * @param dqRates the value for dq_bank_check.dq_rates
     *
     * @mbggenerated
     */
    public void setDqRates(BigDecimal dqRates) {
        this.dqRates = dqRates;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dq_bank_check.active_rates
     *
     * @return the value of dq_bank_check.active_rates
     *
     * @mbggenerated
     */
    public BigDecimal getActiveRates() {
        return activeRates;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dq_bank_check.active_rates
     *
     * @param activeRates the value for dq_bank_check.active_rates
     *
     * @mbggenerated
     */
    public void setActiveRates(BigDecimal activeRates) {
        this.activeRates = activeRates;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dq_bank_check.ticket_rates
     *
     * @return the value of dq_bank_check.ticket_rates
     *
     * @mbggenerated
     */
    public BigDecimal getTicketRates() {
        return ticketRates;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dq_bank_check.ticket_rates
     *
     * @param ticketRates the value for dq_bank_check.ticket_rates
     *
     * @mbggenerated
     */
    public void setTicketRates(BigDecimal ticketRates) {
        this.ticketRates = ticketRates;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dq_bank_check.invest_profit_amt
     *
     * @return the value of dq_bank_check.invest_profit_amt
     *
     * @mbggenerated
     */
    public BigDecimal getInvestProfitAmt() {
        return investProfitAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dq_bank_check.invest_profit_amt
     *
     * @param investProfitAmt the value for dq_bank_check.invest_profit_amt
     *
     * @mbggenerated
     */
    public void setInvestProfitAmt(BigDecimal investProfitAmt) {
        this.investProfitAmt = investProfitAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dq_bank_check.active_profit_amt
     *
     * @return the value of dq_bank_check.active_profit_amt
     *
     * @mbggenerated
     */
    public BigDecimal getActiveProfitAmt() {
        return activeProfitAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dq_bank_check.active_profit_amt
     *
     * @param activeProfitAmt the value for dq_bank_check.active_profit_amt
     *
     * @mbggenerated
     */
    public void setActiveProfitAmt(BigDecimal activeProfitAmt) {
        this.activeProfitAmt = activeProfitAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dq_bank_check.ticket_profit_amt
     *
     * @return the value of dq_bank_check.ticket_profit_amt
     *
     * @mbggenerated
     */
    public BigDecimal getTicketProfitAmt() {
        return ticketProfitAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dq_bank_check.ticket_profit_amt
     *
     * @param ticketProfitAmt the value for dq_bank_check.ticket_profit_amt
     *
     * @mbggenerated
     */
    public void setTicketProfitAmt(BigDecimal ticketProfitAmt) {
        this.ticketProfitAmt = ticketProfitAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dq_bank_check.total_profit_amt
     *
     * @return the value of dq_bank_check.total_profit_amt
     *
     * @mbggenerated
     */
    public BigDecimal getTotalProfitAmt() {
        return totalProfitAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dq_bank_check.total_profit_amt
     *
     * @param totalProfitAmt the value for dq_bank_check.total_profit_amt
     *
     * @mbggenerated
     */
    public void setTotalProfitAmt(BigDecimal totalProfitAmt) {
        this.totalProfitAmt = totalProfitAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dq_bank_check.total_withdraw_amt
     *
     * @return the value of dq_bank_check.total_withdraw_amt
     *
     * @mbggenerated
     */
    public BigDecimal getTotalWithdrawAmt() {
        return totalWithdrawAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dq_bank_check.total_withdraw_amt
     *
     * @param totalWithdrawAmt the value for dq_bank_check.total_withdraw_amt
     *
     * @mbggenerated
     */
    public void setTotalWithdrawAmt(BigDecimal totalWithdrawAmt) {
        this.totalWithdrawAmt = totalWithdrawAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dq_bank_check.invest_time
     *
     * @return the value of dq_bank_check.invest_time
     *
     * @mbggenerated
     */
    public Date getInvestTime() {
        return investTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dq_bank_check.invest_time
     *
     * @param investTime the value for dq_bank_check.invest_time
     *
     * @mbggenerated
     */
    public void setInvestTime(Date investTime) {
        this.investTime = investTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dq_bank_check.invest_days
     *
     * @return the value of dq_bank_check.invest_days
     *
     * @mbggenerated
     */
    public Integer getInvestDays() {
        return investDays;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dq_bank_check.invest_days
     *
     * @param investDays the value for dq_bank_check.invest_days
     *
     * @mbggenerated
     */
    public void setInvestDays(Integer investDays) {
        this.investDays = investDays;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dq_bank_check.end_time
     *
     * @return the value of dq_bank_check.end_time
     *
     * @mbggenerated
     */
    public Date getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dq_bank_check.end_time
     *
     * @param endTime the value for dq_bank_check.end_time
     *
     * @mbggenerated
     */
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dq_bank_check.create_time
     *
     * @return the value of dq_bank_check.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dq_bank_check.create_time
     *
     * @param createTime the value for dq_bank_check.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dq_bank_check.check_status
     *
     * @return the value of dq_bank_check.check_status
     *
     * @mbggenerated
     */
    public String getCheckStatus() {
        return checkStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dq_bank_check.check_status
     *
     * @param checkStatus the value for dq_bank_check.check_status
     *
     * @mbggenerated
     */
    public void setCheckStatus(String checkStatus) {
        this.checkStatus = checkStatus == null ? null : checkStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dq_bank_check.check_time
     *
     * @return the value of dq_bank_check.check_time
     *
     * @mbggenerated
     */
    public Date getCheckTime() {
        return checkTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dq_bank_check.check_time
     *
     * @param checkTime the value for dq_bank_check.check_time
     *
     * @mbggenerated
     */
    public void setCheckTime(Date checkTime) {
        this.checkTime = checkTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dq_bank_check.pay_status
     *
     * @return the value of dq_bank_check.pay_status
     *
     * @mbggenerated
     */
    public String getPayStatus() {
        return payStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dq_bank_check.pay_status
     *
     * @param payStatus the value for dq_bank_check.pay_status
     *
     * @mbggenerated
     */
    public void setPayStatus(String payStatus) {
        this.payStatus = payStatus == null ? null : payStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dq_bank_check.pay_time
     *
     * @return the value of dq_bank_check.pay_time
     *
     * @mbggenerated
     */
    public Date getPayTime() {
        return payTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dq_bank_check.pay_time
     *
     * @param payTime the value for dq_bank_check.pay_time
     *
     * @mbggenerated
     */
    public void setPayTime(Date payTime) {
        this.payTime = payTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dq_bank_check
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", depositBankCheckId=").append(depositBankCheckId);
        sb.append(", userId=").append(userId);
        sb.append(", dqProductId=").append(dqProductId);
        sb.append(", dqTransLogId=").append(dqTransLogId);
        sb.append(", transNo=").append(transNo);
        sb.append(", investAmt=").append(investAmt);
        sb.append(", dqRates=").append(dqRates);
        sb.append(", activeRates=").append(activeRates);
        sb.append(", ticketRates=").append(ticketRates);
        sb.append(", investProfitAmt=").append(investProfitAmt);
        sb.append(", activeProfitAmt=").append(activeProfitAmt);
        sb.append(", ticketProfitAmt=").append(ticketProfitAmt);
        sb.append(", totalProfitAmt=").append(totalProfitAmt);
        sb.append(", totalWithdrawAmt=").append(totalWithdrawAmt);
        sb.append(", investTime=").append(investTime);
        sb.append(", investDays=").append(investDays);
        sb.append(", endTime=").append(endTime);
        sb.append(", createTime=").append(createTime);
        sb.append(", checkStatus=").append(checkStatus);
        sb.append(", checkTime=").append(checkTime);
        sb.append(", payStatus=").append(payStatus);
        sb.append(", payTime=").append(payTime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dq_bank_check
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        DqBankCheck other = (DqBankCheck) that;
        return (this.getDepositBankCheckId() == null ? other.getDepositBankCheckId() == null : this.getDepositBankCheckId().equals(other.getDepositBankCheckId()))
            && (this.getUserId() == null ? other.getUserId() == null : this.getUserId().equals(other.getUserId()))
            && (this.getDqProductId() == null ? other.getDqProductId() == null : this.getDqProductId().equals(other.getDqProductId()))
            && (this.getDqTransLogId() == null ? other.getDqTransLogId() == null : this.getDqTransLogId().equals(other.getDqTransLogId()))
            && (this.getTransNo() == null ? other.getTransNo() == null : this.getTransNo().equals(other.getTransNo()))
            && (this.getInvestAmt() == null ? other.getInvestAmt() == null : this.getInvestAmt().equals(other.getInvestAmt()))
            && (this.getDqRates() == null ? other.getDqRates() == null : this.getDqRates().equals(other.getDqRates()))
            && (this.getActiveRates() == null ? other.getActiveRates() == null : this.getActiveRates().equals(other.getActiveRates()))
            && (this.getTicketRates() == null ? other.getTicketRates() == null : this.getTicketRates().equals(other.getTicketRates()))
            && (this.getInvestProfitAmt() == null ? other.getInvestProfitAmt() == null : this.getInvestProfitAmt().equals(other.getInvestProfitAmt()))
            && (this.getActiveProfitAmt() == null ? other.getActiveProfitAmt() == null : this.getActiveProfitAmt().equals(other.getActiveProfitAmt()))
            && (this.getTicketProfitAmt() == null ? other.getTicketProfitAmt() == null : this.getTicketProfitAmt().equals(other.getTicketProfitAmt()))
            && (this.getTotalProfitAmt() == null ? other.getTotalProfitAmt() == null : this.getTotalProfitAmt().equals(other.getTotalProfitAmt()))
            && (this.getTotalWithdrawAmt() == null ? other.getTotalWithdrawAmt() == null : this.getTotalWithdrawAmt().equals(other.getTotalWithdrawAmt()))
            && (this.getInvestTime() == null ? other.getInvestTime() == null : this.getInvestTime().equals(other.getInvestTime()))
            && (this.getInvestDays() == null ? other.getInvestDays() == null : this.getInvestDays().equals(other.getInvestDays()))
            && (this.getEndTime() == null ? other.getEndTime() == null : this.getEndTime().equals(other.getEndTime()))
            && (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime().equals(other.getCreateTime()))
            && (this.getCheckStatus() == null ? other.getCheckStatus() == null : this.getCheckStatus().equals(other.getCheckStatus()))
            && (this.getCheckTime() == null ? other.getCheckTime() == null : this.getCheckTime().equals(other.getCheckTime()))
            && (this.getPayStatus() == null ? other.getPayStatus() == null : this.getPayStatus().equals(other.getPayStatus()))
            && (this.getPayTime() == null ? other.getPayTime() == null : this.getPayTime().equals(other.getPayTime()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dq_bank_check
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getDepositBankCheckId() == null) ? 0 : getDepositBankCheckId().hashCode());
        result = prime * result + ((getUserId() == null) ? 0 : getUserId().hashCode());
        result = prime * result + ((getDqProductId() == null) ? 0 : getDqProductId().hashCode());
        result = prime * result + ((getDqTransLogId() == null) ? 0 : getDqTransLogId().hashCode());
        result = prime * result + ((getTransNo() == null) ? 0 : getTransNo().hashCode());
        result = prime * result + ((getInvestAmt() == null) ? 0 : getInvestAmt().hashCode());
        result = prime * result + ((getDqRates() == null) ? 0 : getDqRates().hashCode());
        result = prime * result + ((getActiveRates() == null) ? 0 : getActiveRates().hashCode());
        result = prime * result + ((getTicketRates() == null) ? 0 : getTicketRates().hashCode());
        result = prime * result + ((getInvestProfitAmt() == null) ? 0 : getInvestProfitAmt().hashCode());
        result = prime * result + ((getActiveProfitAmt() == null) ? 0 : getActiveProfitAmt().hashCode());
        result = prime * result + ((getTicketProfitAmt() == null) ? 0 : getTicketProfitAmt().hashCode());
        result = prime * result + ((getTotalProfitAmt() == null) ? 0 : getTotalProfitAmt().hashCode());
        result = prime * result + ((getTotalWithdrawAmt() == null) ? 0 : getTotalWithdrawAmt().hashCode());
        result = prime * result + ((getInvestTime() == null) ? 0 : getInvestTime().hashCode());
        result = prime * result + ((getInvestDays() == null) ? 0 : getInvestDays().hashCode());
        result = prime * result + ((getEndTime() == null) ? 0 : getEndTime().hashCode());
        result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
        result = prime * result + ((getCheckStatus() == null) ? 0 : getCheckStatus().hashCode());
        result = prime * result + ((getCheckTime() == null) ? 0 : getCheckTime().hashCode());
        result = prime * result + ((getPayStatus() == null) ? 0 : getPayStatus().hashCode());
        result = prime * result + ((getPayTime() == null) ? 0 : getPayTime().hashCode());
        return result;
    }
}