package com.p2g.mybatis.model.generator;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class DqTicket implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dq_ticket.dq_ticket_id
     *
     * @mbggenerated
     */
    private Long dqTicketId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dq_ticket.user_id
     *
     * @mbggenerated
     */
    private Long userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dq_ticket.dq_product_id
     *
     * @mbggenerated
     */
    private Long dqProductId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dq_ticket.inc_rates
     *
     * @mbggenerated
     */
    private BigDecimal incRates;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dq_ticket.inc_days
     *
     * @mbggenerated
     */
    private Integer incDays;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dq_ticket.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dq_ticket.expired_time
     *
     * @mbggenerated
     */
    private Date expiredTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dq_ticket.status
     *
     * @mbggenerated
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dq_ticket.used_time
     *
     * @mbggenerated
     */
    private Date usedTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dq_ticket.source
     *
     * @mbggenerated
     */
    private String source;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table dq_ticket
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dq_ticket.dq_ticket_id
     *
     * @return the value of dq_ticket.dq_ticket_id
     *
     * @mbggenerated
     */
    public Long getDqTicketId() {
        return dqTicketId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dq_ticket.dq_ticket_id
     *
     * @param dqTicketId the value for dq_ticket.dq_ticket_id
     *
     * @mbggenerated
     */
    public void setDqTicketId(Long dqTicketId) {
        this.dqTicketId = dqTicketId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dq_ticket.user_id
     *
     * @return the value of dq_ticket.user_id
     *
     * @mbggenerated
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dq_ticket.user_id
     *
     * @param userId the value for dq_ticket.user_id
     *
     * @mbggenerated
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dq_ticket.dq_product_id
     *
     * @return the value of dq_ticket.dq_product_id
     *
     * @mbggenerated
     */
    public Long getDqProductId() {
        return dqProductId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dq_ticket.dq_product_id
     *
     * @param dqProductId the value for dq_ticket.dq_product_id
     *
     * @mbggenerated
     */
    public void setDqProductId(Long dqProductId) {
        this.dqProductId = dqProductId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dq_ticket.inc_rates
     *
     * @return the value of dq_ticket.inc_rates
     *
     * @mbggenerated
     */
    public BigDecimal getIncRates() {
        return incRates;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dq_ticket.inc_rates
     *
     * @param incRates the value for dq_ticket.inc_rates
     *
     * @mbggenerated
     */
    public void setIncRates(BigDecimal incRates) {
        this.incRates = incRates;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dq_ticket.inc_days
     *
     * @return the value of dq_ticket.inc_days
     *
     * @mbggenerated
     */
    public Integer getIncDays() {
        return incDays;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dq_ticket.inc_days
     *
     * @param incDays the value for dq_ticket.inc_days
     *
     * @mbggenerated
     */
    public void setIncDays(Integer incDays) {
        this.incDays = incDays;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dq_ticket.create_time
     *
     * @return the value of dq_ticket.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dq_ticket.create_time
     *
     * @param createTime the value for dq_ticket.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dq_ticket.expired_time
     *
     * @return the value of dq_ticket.expired_time
     *
     * @mbggenerated
     */
    public Date getExpiredTime() {
        return expiredTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dq_ticket.expired_time
     *
     * @param expiredTime the value for dq_ticket.expired_time
     *
     * @mbggenerated
     */
    public void setExpiredTime(Date expiredTime) {
        this.expiredTime = expiredTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dq_ticket.status
     *
     * @return the value of dq_ticket.status
     *
     * @mbggenerated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dq_ticket.status
     *
     * @param status the value for dq_ticket.status
     *
     * @mbggenerated
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dq_ticket.used_time
     *
     * @return the value of dq_ticket.used_time
     *
     * @mbggenerated
     */
    public Date getUsedTime() {
        return usedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dq_ticket.used_time
     *
     * @param usedTime the value for dq_ticket.used_time
     *
     * @mbggenerated
     */
    public void setUsedTime(Date usedTime) {
        this.usedTime = usedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dq_ticket.source
     *
     * @return the value of dq_ticket.source
     *
     * @mbggenerated
     */
    public String getSource() {
        return source;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dq_ticket.source
     *
     * @param source the value for dq_ticket.source
     *
     * @mbggenerated
     */
    public void setSource(String source) {
        this.source = source == null ? null : source.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dq_ticket
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", dqTicketId=").append(dqTicketId);
        sb.append(", userId=").append(userId);
        sb.append(", dqProductId=").append(dqProductId);
        sb.append(", incRates=").append(incRates);
        sb.append(", incDays=").append(incDays);
        sb.append(", createTime=").append(createTime);
        sb.append(", expiredTime=").append(expiredTime);
        sb.append(", status=").append(status);
        sb.append(", usedTime=").append(usedTime);
        sb.append(", source=").append(source);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dq_ticket
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        DqTicket other = (DqTicket) that;
        return (this.getDqTicketId() == null ? other.getDqTicketId() == null : this.getDqTicketId().equals(other.getDqTicketId()))
            && (this.getUserId() == null ? other.getUserId() == null : this.getUserId().equals(other.getUserId()))
            && (this.getDqProductId() == null ? other.getDqProductId() == null : this.getDqProductId().equals(other.getDqProductId()))
            && (this.getIncRates() == null ? other.getIncRates() == null : this.getIncRates().equals(other.getIncRates()))
            && (this.getIncDays() == null ? other.getIncDays() == null : this.getIncDays().equals(other.getIncDays()))
            && (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime().equals(other.getCreateTime()))
            && (this.getExpiredTime() == null ? other.getExpiredTime() == null : this.getExpiredTime().equals(other.getExpiredTime()))
            && (this.getStatus() == null ? other.getStatus() == null : this.getStatus().equals(other.getStatus()))
            && (this.getUsedTime() == null ? other.getUsedTime() == null : this.getUsedTime().equals(other.getUsedTime()))
            && (this.getSource() == null ? other.getSource() == null : this.getSource().equals(other.getSource()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dq_ticket
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getDqTicketId() == null) ? 0 : getDqTicketId().hashCode());
        result = prime * result + ((getUserId() == null) ? 0 : getUserId().hashCode());
        result = prime * result + ((getDqProductId() == null) ? 0 : getDqProductId().hashCode());
        result = prime * result + ((getIncRates() == null) ? 0 : getIncRates().hashCode());
        result = prime * result + ((getIncDays() == null) ? 0 : getIncDays().hashCode());
        result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
        result = prime * result + ((getExpiredTime() == null) ? 0 : getExpiredTime().hashCode());
        result = prime * result + ((getStatus() == null) ? 0 : getStatus().hashCode());
        result = prime * result + ((getUsedTime() == null) ? 0 : getUsedTime().hashCode());
        result = prime * result + ((getSource() == null) ? 0 : getSource().hashCode());
        return result;
    }
}