package com.p2g.mybatis.model.generator;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class DqTransLog implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dq_trans_log.dq_trans_log_id
     *
     * @mbggenerated
     */
    private Long dqTransLogId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dq_trans_log.user_id
     *
     * @mbggenerated
     */
    private Long userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dq_trans_log.dq_product_id
     *
     * @mbggenerated
     */
    private Long dqProductId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dq_trans_log.trans_no
     *
     * @mbggenerated
     */
    private String transNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dq_trans_log.invest_time
     *
     * @mbggenerated
     */
    private Date investTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dq_trans_log.invest_days
     *
     * @mbggenerated
     */
    private Integer investDays;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dq_trans_log.end_time
     *
     * @mbggenerated
     */
    private Date endTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dq_trans_log.dq_rates
     *
     * @mbggenerated
     */
    private BigDecimal dqRates;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dq_trans_log.active_rates
     *
     * @mbggenerated
     */
    private BigDecimal activeRates;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dq_trans_log.invest_amt
     *
     * @mbggenerated
     */
    private BigDecimal investAmt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dq_trans_log.total_profit_amt
     *
     * @mbggenerated
     */
    private BigDecimal totalProfitAmt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dq_trans_log.invest_profit_amt
     *
     * @mbggenerated
     */
    private BigDecimal investProfitAmt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dq_trans_log.active_profit_amt
     *
     * @mbggenerated
     */
    private String activeProfitAmt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dq_trans_log.end_deal
     *
     * @mbggenerated
     */
    private String endDeal;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dq_trans_log.continue_product_id
     *
     * @mbggenerated
     */
    private Long continueProductId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dq_trans_log.continue_auto_ticket
     *
     * @mbggenerated
     */
    private String continueAutoTicket;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dq_trans_log.end_deal_time
     *
     * @mbggenerated
     */
    private Date endDealTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dq_trans_log.fund_source
     *
     * @mbggenerated
     */
    private String fundSource;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dq_trans_log.platform_source
     *
     * @mbggenerated
     */
    private String platformSource;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dq_trans_log.dq_ticket_id
     *
     * @mbggenerated
     */
    private Long dqTicketId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dq_trans_log.ticket_rates
     *
     * @mbggenerated
     */
    private BigDecimal ticketRates;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dq_trans_log.ticket_profit_amt
     *
     * @mbggenerated
     */
    private BigDecimal ticketProfitAmt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dq_trans_log.status
     *
     * @mbggenerated
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dq_trans_log.close_time
     *
     * @mbggenerated
     */
    private Date closeTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table dq_trans_log
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dq_trans_log.dq_trans_log_id
     *
     * @return the value of dq_trans_log.dq_trans_log_id
     *
     * @mbggenerated
     */
    public Long getDqTransLogId() {
        return dqTransLogId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dq_trans_log.dq_trans_log_id
     *
     * @param dqTransLogId the value for dq_trans_log.dq_trans_log_id
     *
     * @mbggenerated
     */
    public void setDqTransLogId(Long dqTransLogId) {
        this.dqTransLogId = dqTransLogId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dq_trans_log.user_id
     *
     * @return the value of dq_trans_log.user_id
     *
     * @mbggenerated
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dq_trans_log.user_id
     *
     * @param userId the value for dq_trans_log.user_id
     *
     * @mbggenerated
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dq_trans_log.dq_product_id
     *
     * @return the value of dq_trans_log.dq_product_id
     *
     * @mbggenerated
     */
    public Long getDqProductId() {
        return dqProductId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dq_trans_log.dq_product_id
     *
     * @param dqProductId the value for dq_trans_log.dq_product_id
     *
     * @mbggenerated
     */
    public void setDqProductId(Long dqProductId) {
        this.dqProductId = dqProductId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dq_trans_log.trans_no
     *
     * @return the value of dq_trans_log.trans_no
     *
     * @mbggenerated
     */
    public String getTransNo() {
        return transNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dq_trans_log.trans_no
     *
     * @param transNo the value for dq_trans_log.trans_no
     *
     * @mbggenerated
     */
    public void setTransNo(String transNo) {
        this.transNo = transNo == null ? null : transNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dq_trans_log.invest_time
     *
     * @return the value of dq_trans_log.invest_time
     *
     * @mbggenerated
     */
    public Date getInvestTime() {
        return investTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dq_trans_log.invest_time
     *
     * @param investTime the value for dq_trans_log.invest_time
     *
     * @mbggenerated
     */
    public void setInvestTime(Date investTime) {
        this.investTime = investTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dq_trans_log.invest_days
     *
     * @return the value of dq_trans_log.invest_days
     *
     * @mbggenerated
     */
    public Integer getInvestDays() {
        return investDays;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dq_trans_log.invest_days
     *
     * @param investDays the value for dq_trans_log.invest_days
     *
     * @mbggenerated
     */
    public void setInvestDays(Integer investDays) {
        this.investDays = investDays;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dq_trans_log.end_time
     *
     * @return the value of dq_trans_log.end_time
     *
     * @mbggenerated
     */
    public Date getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dq_trans_log.end_time
     *
     * @param endTime the value for dq_trans_log.end_time
     *
     * @mbggenerated
     */
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dq_trans_log.dq_rates
     *
     * @return the value of dq_trans_log.dq_rates
     *
     * @mbggenerated
     */
    public BigDecimal getDqRates() {
        return dqRates;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dq_trans_log.dq_rates
     *
     * @param dqRates the value for dq_trans_log.dq_rates
     *
     * @mbggenerated
     */
    public void setDqRates(BigDecimal dqRates) {
        this.dqRates = dqRates;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dq_trans_log.active_rates
     *
     * @return the value of dq_trans_log.active_rates
     *
     * @mbggenerated
     */
    public BigDecimal getActiveRates() {
        return activeRates;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dq_trans_log.active_rates
     *
     * @param activeRates the value for dq_trans_log.active_rates
     *
     * @mbggenerated
     */
    public void setActiveRates(BigDecimal activeRates) {
        this.activeRates = activeRates;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dq_trans_log.invest_amt
     *
     * @return the value of dq_trans_log.invest_amt
     *
     * @mbggenerated
     */
    public BigDecimal getInvestAmt() {
        return investAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dq_trans_log.invest_amt
     *
     * @param investAmt the value for dq_trans_log.invest_amt
     *
     * @mbggenerated
     */
    public void setInvestAmt(BigDecimal investAmt) {
        this.investAmt = investAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dq_trans_log.total_profit_amt
     *
     * @return the value of dq_trans_log.total_profit_amt
     *
     * @mbggenerated
     */
    public BigDecimal getTotalProfitAmt() {
        return totalProfitAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dq_trans_log.total_profit_amt
     *
     * @param totalProfitAmt the value for dq_trans_log.total_profit_amt
     *
     * @mbggenerated
     */
    public void setTotalProfitAmt(BigDecimal totalProfitAmt) {
        this.totalProfitAmt = totalProfitAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dq_trans_log.invest_profit_amt
     *
     * @return the value of dq_trans_log.invest_profit_amt
     *
     * @mbggenerated
     */
    public BigDecimal getInvestProfitAmt() {
        return investProfitAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dq_trans_log.invest_profit_amt
     *
     * @param investProfitAmt the value for dq_trans_log.invest_profit_amt
     *
     * @mbggenerated
     */
    public void setInvestProfitAmt(BigDecimal investProfitAmt) {
        this.investProfitAmt = investProfitAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dq_trans_log.active_profit_amt
     *
     * @return the value of dq_trans_log.active_profit_amt
     *
     * @mbggenerated
     */
    public String getActiveProfitAmt() {
        return activeProfitAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dq_trans_log.active_profit_amt
     *
     * @param activeProfitAmt the value for dq_trans_log.active_profit_amt
     *
     * @mbggenerated
     */
    public void setActiveProfitAmt(String activeProfitAmt) {
        this.activeProfitAmt = activeProfitAmt == null ? null : activeProfitAmt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dq_trans_log.end_deal
     *
     * @return the value of dq_trans_log.end_deal
     *
     * @mbggenerated
     */
    public String getEndDeal() {
        return endDeal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dq_trans_log.end_deal
     *
     * @param endDeal the value for dq_trans_log.end_deal
     *
     * @mbggenerated
     */
    public void setEndDeal(String endDeal) {
        this.endDeal = endDeal == null ? null : endDeal.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dq_trans_log.continue_product_id
     *
     * @return the value of dq_trans_log.continue_product_id
     *
     * @mbggenerated
     */
    public Long getContinueProductId() {
        return continueProductId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dq_trans_log.continue_product_id
     *
     * @param continueProductId the value for dq_trans_log.continue_product_id
     *
     * @mbggenerated
     */
    public void setContinueProductId(Long continueProductId) {
        this.continueProductId = continueProductId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dq_trans_log.continue_auto_ticket
     *
     * @return the value of dq_trans_log.continue_auto_ticket
     *
     * @mbggenerated
     */
    public String getContinueAutoTicket() {
        return continueAutoTicket;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dq_trans_log.continue_auto_ticket
     *
     * @param continueAutoTicket the value for dq_trans_log.continue_auto_ticket
     *
     * @mbggenerated
     */
    public void setContinueAutoTicket(String continueAutoTicket) {
        this.continueAutoTicket = continueAutoTicket == null ? null : continueAutoTicket.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dq_trans_log.end_deal_time
     *
     * @return the value of dq_trans_log.end_deal_time
     *
     * @mbggenerated
     */
    public Date getEndDealTime() {
        return endDealTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dq_trans_log.end_deal_time
     *
     * @param endDealTime the value for dq_trans_log.end_deal_time
     *
     * @mbggenerated
     */
    public void setEndDealTime(Date endDealTime) {
        this.endDealTime = endDealTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dq_trans_log.fund_source
     *
     * @return the value of dq_trans_log.fund_source
     *
     * @mbggenerated
     */
    public String getFundSource() {
        return fundSource;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dq_trans_log.fund_source
     *
     * @param fundSource the value for dq_trans_log.fund_source
     *
     * @mbggenerated
     */
    public void setFundSource(String fundSource) {
        this.fundSource = fundSource == null ? null : fundSource.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dq_trans_log.platform_source
     *
     * @return the value of dq_trans_log.platform_source
     *
     * @mbggenerated
     */
    public String getPlatformSource() {
        return platformSource;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dq_trans_log.platform_source
     *
     * @param platformSource the value for dq_trans_log.platform_source
     *
     * @mbggenerated
     */
    public void setPlatformSource(String platformSource) {
        this.platformSource = platformSource == null ? null : platformSource.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dq_trans_log.dq_ticket_id
     *
     * @return the value of dq_trans_log.dq_ticket_id
     *
     * @mbggenerated
     */
    public Long getDqTicketId() {
        return dqTicketId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dq_trans_log.dq_ticket_id
     *
     * @param dqTicketId the value for dq_trans_log.dq_ticket_id
     *
     * @mbggenerated
     */
    public void setDqTicketId(Long dqTicketId) {
        this.dqTicketId = dqTicketId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dq_trans_log.ticket_rates
     *
     * @return the value of dq_trans_log.ticket_rates
     *
     * @mbggenerated
     */
    public BigDecimal getTicketRates() {
        return ticketRates;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dq_trans_log.ticket_rates
     *
     * @param ticketRates the value for dq_trans_log.ticket_rates
     *
     * @mbggenerated
     */
    public void setTicketRates(BigDecimal ticketRates) {
        this.ticketRates = ticketRates;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dq_trans_log.ticket_profit_amt
     *
     * @return the value of dq_trans_log.ticket_profit_amt
     *
     * @mbggenerated
     */
    public BigDecimal getTicketProfitAmt() {
        return ticketProfitAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dq_trans_log.ticket_profit_amt
     *
     * @param ticketProfitAmt the value for dq_trans_log.ticket_profit_amt
     *
     * @mbggenerated
     */
    public void setTicketProfitAmt(BigDecimal ticketProfitAmt) {
        this.ticketProfitAmt = ticketProfitAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dq_trans_log.status
     *
     * @return the value of dq_trans_log.status
     *
     * @mbggenerated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dq_trans_log.status
     *
     * @param status the value for dq_trans_log.status
     *
     * @mbggenerated
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dq_trans_log.close_time
     *
     * @return the value of dq_trans_log.close_time
     *
     * @mbggenerated
     */
    public Date getCloseTime() {
        return closeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dq_trans_log.close_time
     *
     * @param closeTime the value for dq_trans_log.close_time
     *
     * @mbggenerated
     */
    public void setCloseTime(Date closeTime) {
        this.closeTime = closeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dq_trans_log
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", dqTransLogId=").append(dqTransLogId);
        sb.append(", userId=").append(userId);
        sb.append(", dqProductId=").append(dqProductId);
        sb.append(", transNo=").append(transNo);
        sb.append(", investTime=").append(investTime);
        sb.append(", investDays=").append(investDays);
        sb.append(", endTime=").append(endTime);
        sb.append(", dqRates=").append(dqRates);
        sb.append(", activeRates=").append(activeRates);
        sb.append(", investAmt=").append(investAmt);
        sb.append(", totalProfitAmt=").append(totalProfitAmt);
        sb.append(", investProfitAmt=").append(investProfitAmt);
        sb.append(", activeProfitAmt=").append(activeProfitAmt);
        sb.append(", endDeal=").append(endDeal);
        sb.append(", continueProductId=").append(continueProductId);
        sb.append(", continueAutoTicket=").append(continueAutoTicket);
        sb.append(", endDealTime=").append(endDealTime);
        sb.append(", fundSource=").append(fundSource);
        sb.append(", platformSource=").append(platformSource);
        sb.append(", dqTicketId=").append(dqTicketId);
        sb.append(", ticketRates=").append(ticketRates);
        sb.append(", ticketProfitAmt=").append(ticketProfitAmt);
        sb.append(", status=").append(status);
        sb.append(", closeTime=").append(closeTime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dq_trans_log
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        DqTransLog other = (DqTransLog) that;
        return (this.getDqTransLogId() == null ? other.getDqTransLogId() == null : this.getDqTransLogId().equals(other.getDqTransLogId()))
            && (this.getUserId() == null ? other.getUserId() == null : this.getUserId().equals(other.getUserId()))
            && (this.getDqProductId() == null ? other.getDqProductId() == null : this.getDqProductId().equals(other.getDqProductId()))
            && (this.getTransNo() == null ? other.getTransNo() == null : this.getTransNo().equals(other.getTransNo()))
            && (this.getInvestTime() == null ? other.getInvestTime() == null : this.getInvestTime().equals(other.getInvestTime()))
            && (this.getInvestDays() == null ? other.getInvestDays() == null : this.getInvestDays().equals(other.getInvestDays()))
            && (this.getEndTime() == null ? other.getEndTime() == null : this.getEndTime().equals(other.getEndTime()))
            && (this.getDqRates() == null ? other.getDqRates() == null : this.getDqRates().equals(other.getDqRates()))
            && (this.getActiveRates() == null ? other.getActiveRates() == null : this.getActiveRates().equals(other.getActiveRates()))
            && (this.getInvestAmt() == null ? other.getInvestAmt() == null : this.getInvestAmt().equals(other.getInvestAmt()))
            && (this.getTotalProfitAmt() == null ? other.getTotalProfitAmt() == null : this.getTotalProfitAmt().equals(other.getTotalProfitAmt()))
            && (this.getInvestProfitAmt() == null ? other.getInvestProfitAmt() == null : this.getInvestProfitAmt().equals(other.getInvestProfitAmt()))
            && (this.getActiveProfitAmt() == null ? other.getActiveProfitAmt() == null : this.getActiveProfitAmt().equals(other.getActiveProfitAmt()))
            && (this.getEndDeal() == null ? other.getEndDeal() == null : this.getEndDeal().equals(other.getEndDeal()))
            && (this.getContinueProductId() == null ? other.getContinueProductId() == null : this.getContinueProductId().equals(other.getContinueProductId()))
            && (this.getContinueAutoTicket() == null ? other.getContinueAutoTicket() == null : this.getContinueAutoTicket().equals(other.getContinueAutoTicket()))
            && (this.getEndDealTime() == null ? other.getEndDealTime() == null : this.getEndDealTime().equals(other.getEndDealTime()))
            && (this.getFundSource() == null ? other.getFundSource() == null : this.getFundSource().equals(other.getFundSource()))
            && (this.getPlatformSource() == null ? other.getPlatformSource() == null : this.getPlatformSource().equals(other.getPlatformSource()))
            && (this.getDqTicketId() == null ? other.getDqTicketId() == null : this.getDqTicketId().equals(other.getDqTicketId()))
            && (this.getTicketRates() == null ? other.getTicketRates() == null : this.getTicketRates().equals(other.getTicketRates()))
            && (this.getTicketProfitAmt() == null ? other.getTicketProfitAmt() == null : this.getTicketProfitAmt().equals(other.getTicketProfitAmt()))
            && (this.getStatus() == null ? other.getStatus() == null : this.getStatus().equals(other.getStatus()))
            && (this.getCloseTime() == null ? other.getCloseTime() == null : this.getCloseTime().equals(other.getCloseTime()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dq_trans_log
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getDqTransLogId() == null) ? 0 : getDqTransLogId().hashCode());
        result = prime * result + ((getUserId() == null) ? 0 : getUserId().hashCode());
        result = prime * result + ((getDqProductId() == null) ? 0 : getDqProductId().hashCode());
        result = prime * result + ((getTransNo() == null) ? 0 : getTransNo().hashCode());
        result = prime * result + ((getInvestTime() == null) ? 0 : getInvestTime().hashCode());
        result = prime * result + ((getInvestDays() == null) ? 0 : getInvestDays().hashCode());
        result = prime * result + ((getEndTime() == null) ? 0 : getEndTime().hashCode());
        result = prime * result + ((getDqRates() == null) ? 0 : getDqRates().hashCode());
        result = prime * result + ((getActiveRates() == null) ? 0 : getActiveRates().hashCode());
        result = prime * result + ((getInvestAmt() == null) ? 0 : getInvestAmt().hashCode());
        result = prime * result + ((getTotalProfitAmt() == null) ? 0 : getTotalProfitAmt().hashCode());
        result = prime * result + ((getInvestProfitAmt() == null) ? 0 : getInvestProfitAmt().hashCode());
        result = prime * result + ((getActiveProfitAmt() == null) ? 0 : getActiveProfitAmt().hashCode());
        result = prime * result + ((getEndDeal() == null) ? 0 : getEndDeal().hashCode());
        result = prime * result + ((getContinueProductId() == null) ? 0 : getContinueProductId().hashCode());
        result = prime * result + ((getContinueAutoTicket() == null) ? 0 : getContinueAutoTicket().hashCode());
        result = prime * result + ((getEndDealTime() == null) ? 0 : getEndDealTime().hashCode());
        result = prime * result + ((getFundSource() == null) ? 0 : getFundSource().hashCode());
        result = prime * result + ((getPlatformSource() == null) ? 0 : getPlatformSource().hashCode());
        result = prime * result + ((getDqTicketId() == null) ? 0 : getDqTicketId().hashCode());
        result = prime * result + ((getTicketRates() == null) ? 0 : getTicketRates().hashCode());
        result = prime * result + ((getTicketProfitAmt() == null) ? 0 : getTicketProfitAmt().hashCode());
        result = prime * result + ((getStatus() == null) ? 0 : getStatus().hashCode());
        result = prime * result + ((getCloseTime() == null) ? 0 : getCloseTime().hashCode());
        return result;
    }
}