package com.p2g.mybatis.model.generator;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class FundTransList implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fund_trans_list.fund_trans_list_id
     *
     * @mbggenerated
     */
    private Long fundTransListId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fund_trans_list.user_id
     *
     * @mbggenerated
     */
    private Long userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fund_trans_list.trans_no
     *
     * @mbggenerated
     */
    private String transNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fund_trans_list.pay_no
     *
     * @mbggenerated
     */
    private String payNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fund_trans_list.kind
     *
     * @mbggenerated
     */
    private String kind;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fund_trans_list.income_kind
     *
     * @mbggenerated
     */
    private String incomeKind;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fund_trans_list.trans_date
     *
     * @mbggenerated
     */
    private String transDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fund_trans_list.trans_amt
     *
     * @mbggenerated
     */
    private BigDecimal transAmt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fund_trans_list.remark
     *
     * @mbggenerated
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fund_trans_list.trans_time
     *
     * @mbggenerated
     */
    private Date transTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fund_trans_list.trans_fee
     *
     * @mbggenerated
     */
    private BigDecimal transFee;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table fund_trans_list
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fund_trans_list.fund_trans_list_id
     *
     * @return the value of fund_trans_list.fund_trans_list_id
     *
     * @mbggenerated
     */
    public Long getFundTransListId() {
        return fundTransListId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fund_trans_list.fund_trans_list_id
     *
     * @param fundTransListId the value for fund_trans_list.fund_trans_list_id
     *
     * @mbggenerated
     */
    public void setFundTransListId(Long fundTransListId) {
        this.fundTransListId = fundTransListId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fund_trans_list.user_id
     *
     * @return the value of fund_trans_list.user_id
     *
     * @mbggenerated
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fund_trans_list.user_id
     *
     * @param userId the value for fund_trans_list.user_id
     *
     * @mbggenerated
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fund_trans_list.trans_no
     *
     * @return the value of fund_trans_list.trans_no
     *
     * @mbggenerated
     */
    public String getTransNo() {
        return transNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fund_trans_list.trans_no
     *
     * @param transNo the value for fund_trans_list.trans_no
     *
     * @mbggenerated
     */
    public void setTransNo(String transNo) {
        this.transNo = transNo == null ? null : transNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fund_trans_list.pay_no
     *
     * @return the value of fund_trans_list.pay_no
     *
     * @mbggenerated
     */
    public String getPayNo() {
        return payNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fund_trans_list.pay_no
     *
     * @param payNo the value for fund_trans_list.pay_no
     *
     * @mbggenerated
     */
    public void setPayNo(String payNo) {
        this.payNo = payNo == null ? null : payNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fund_trans_list.kind
     *
     * @return the value of fund_trans_list.kind
     *
     * @mbggenerated
     */
    public String getKind() {
        return kind;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fund_trans_list.kind
     *
     * @param kind the value for fund_trans_list.kind
     *
     * @mbggenerated
     */
    public void setKind(String kind) {
        this.kind = kind == null ? null : kind.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fund_trans_list.income_kind
     *
     * @return the value of fund_trans_list.income_kind
     *
     * @mbggenerated
     */
    public String getIncomeKind() {
        return incomeKind;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fund_trans_list.income_kind
     *
     * @param incomeKind the value for fund_trans_list.income_kind
     *
     * @mbggenerated
     */
    public void setIncomeKind(String incomeKind) {
        this.incomeKind = incomeKind == null ? null : incomeKind.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fund_trans_list.trans_date
     *
     * @return the value of fund_trans_list.trans_date
     *
     * @mbggenerated
     */
    public String getTransDate() {
        return transDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fund_trans_list.trans_date
     *
     * @param transDate the value for fund_trans_list.trans_date
     *
     * @mbggenerated
     */
    public void setTransDate(String transDate) {
        this.transDate = transDate == null ? null : transDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fund_trans_list.trans_amt
     *
     * @return the value of fund_trans_list.trans_amt
     *
     * @mbggenerated
     */
    public BigDecimal getTransAmt() {
        return transAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fund_trans_list.trans_amt
     *
     * @param transAmt the value for fund_trans_list.trans_amt
     *
     * @mbggenerated
     */
    public void setTransAmt(BigDecimal transAmt) {
        this.transAmt = transAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fund_trans_list.remark
     *
     * @return the value of fund_trans_list.remark
     *
     * @mbggenerated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fund_trans_list.remark
     *
     * @param remark the value for fund_trans_list.remark
     *
     * @mbggenerated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fund_trans_list.trans_time
     *
     * @return the value of fund_trans_list.trans_time
     *
     * @mbggenerated
     */
    public Date getTransTime() {
        return transTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fund_trans_list.trans_time
     *
     * @param transTime the value for fund_trans_list.trans_time
     *
     * @mbggenerated
     */
    public void setTransTime(Date transTime) {
        this.transTime = transTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fund_trans_list.trans_fee
     *
     * @return the value of fund_trans_list.trans_fee
     *
     * @mbggenerated
     */
    public BigDecimal getTransFee() {
        return transFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fund_trans_list.trans_fee
     *
     * @param transFee the value for fund_trans_list.trans_fee
     *
     * @mbggenerated
     */
    public void setTransFee(BigDecimal transFee) {
        this.transFee = transFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fund_trans_list
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", fundTransListId=").append(fundTransListId);
        sb.append(", userId=").append(userId);
        sb.append(", transNo=").append(transNo);
        sb.append(", payNo=").append(payNo);
        sb.append(", kind=").append(kind);
        sb.append(", incomeKind=").append(incomeKind);
        sb.append(", transDate=").append(transDate);
        sb.append(", transAmt=").append(transAmt);
        sb.append(", remark=").append(remark);
        sb.append(", transTime=").append(transTime);
        sb.append(", transFee=").append(transFee);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fund_trans_list
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        FundTransList other = (FundTransList) that;
        return (this.getFundTransListId() == null ? other.getFundTransListId() == null : this.getFundTransListId().equals(other.getFundTransListId()))
            && (this.getUserId() == null ? other.getUserId() == null : this.getUserId().equals(other.getUserId()))
            && (this.getTransNo() == null ? other.getTransNo() == null : this.getTransNo().equals(other.getTransNo()))
            && (this.getPayNo() == null ? other.getPayNo() == null : this.getPayNo().equals(other.getPayNo()))
            && (this.getKind() == null ? other.getKind() == null : this.getKind().equals(other.getKind()))
            && (this.getIncomeKind() == null ? other.getIncomeKind() == null : this.getIncomeKind().equals(other.getIncomeKind()))
            && (this.getTransDate() == null ? other.getTransDate() == null : this.getTransDate().equals(other.getTransDate()))
            && (this.getTransAmt() == null ? other.getTransAmt() == null : this.getTransAmt().equals(other.getTransAmt()))
            && (this.getRemark() == null ? other.getRemark() == null : this.getRemark().equals(other.getRemark()))
            && (this.getTransTime() == null ? other.getTransTime() == null : this.getTransTime().equals(other.getTransTime()))
            && (this.getTransFee() == null ? other.getTransFee() == null : this.getTransFee().equals(other.getTransFee()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fund_trans_list
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getFundTransListId() == null) ? 0 : getFundTransListId().hashCode());
        result = prime * result + ((getUserId() == null) ? 0 : getUserId().hashCode());
        result = prime * result + ((getTransNo() == null) ? 0 : getTransNo().hashCode());
        result = prime * result + ((getPayNo() == null) ? 0 : getPayNo().hashCode());
        result = prime * result + ((getKind() == null) ? 0 : getKind().hashCode());
        result = prime * result + ((getIncomeKind() == null) ? 0 : getIncomeKind().hashCode());
        result = prime * result + ((getTransDate() == null) ? 0 : getTransDate().hashCode());
        result = prime * result + ((getTransAmt() == null) ? 0 : getTransAmt().hashCode());
        result = prime * result + ((getRemark() == null) ? 0 : getRemark().hashCode());
        result = prime * result + ((getTransTime() == null) ? 0 : getTransTime().hashCode());
        result = prime * result + ((getTransFee() == null) ? 0 : getTransFee().hashCode());
        return result;
    }
}