package com.p2g.mybatis.model.generator;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class HqCoupon implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hq_coupon.hq_coupon_id
     *
     * @mbggenerated
     */
    private Integer hqCouponId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hq_coupon.user_id
     *
     * @mbggenerated
     */
    private Long userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hq_coupon.inc_days
     *
     * @mbggenerated
     */
    private Integer incDays;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hq_coupon.inc_rates
     *
     * @mbggenerated
     */
    private BigDecimal incRates;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hq_coupon.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hq_coupon.expired_time
     *
     * @mbggenerated
     */
    private Date expiredTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hq_coupon.used_time
     *
     * @mbggenerated
     */
    private Date usedTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hq_coupon.source
     *
     * @mbggenerated
     */
    private String source;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hq_coupon.status
     *
     * @mbggenerated
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hq_coupon.admin_name
     *
     * @mbggenerated
     */
    private String adminName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table hq_coupon
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hq_coupon.hq_coupon_id
     *
     * @return the value of hq_coupon.hq_coupon_id
     *
     * @mbggenerated
     */
    public Integer getHqCouponId() {
        return hqCouponId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hq_coupon.hq_coupon_id
     *
     * @param hqCouponId the value for hq_coupon.hq_coupon_id
     *
     * @mbggenerated
     */
    public void setHqCouponId(Integer hqCouponId) {
        this.hqCouponId = hqCouponId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hq_coupon.user_id
     *
     * @return the value of hq_coupon.user_id
     *
     * @mbggenerated
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hq_coupon.user_id
     *
     * @param userId the value for hq_coupon.user_id
     *
     * @mbggenerated
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hq_coupon.inc_days
     *
     * @return the value of hq_coupon.inc_days
     *
     * @mbggenerated
     */
    public Integer getIncDays() {
        return incDays;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hq_coupon.inc_days
     *
     * @param incDays the value for hq_coupon.inc_days
     *
     * @mbggenerated
     */
    public void setIncDays(Integer incDays) {
        this.incDays = incDays;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hq_coupon.inc_rates
     *
     * @return the value of hq_coupon.inc_rates
     *
     * @mbggenerated
     */
    public BigDecimal getIncRates() {
        return incRates;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hq_coupon.inc_rates
     *
     * @param incRates the value for hq_coupon.inc_rates
     *
     * @mbggenerated
     */
    public void setIncRates(BigDecimal incRates) {
        this.incRates = incRates;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hq_coupon.create_time
     *
     * @return the value of hq_coupon.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hq_coupon.create_time
     *
     * @param createTime the value for hq_coupon.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hq_coupon.expired_time
     *
     * @return the value of hq_coupon.expired_time
     *
     * @mbggenerated
     */
    public Date getExpiredTime() {
        return expiredTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hq_coupon.expired_time
     *
     * @param expiredTime the value for hq_coupon.expired_time
     *
     * @mbggenerated
     */
    public void setExpiredTime(Date expiredTime) {
        this.expiredTime = expiredTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hq_coupon.used_time
     *
     * @return the value of hq_coupon.used_time
     *
     * @mbggenerated
     */
    public Date getUsedTime() {
        return usedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hq_coupon.used_time
     *
     * @param usedTime the value for hq_coupon.used_time
     *
     * @mbggenerated
     */
    public void setUsedTime(Date usedTime) {
        this.usedTime = usedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hq_coupon.source
     *
     * @return the value of hq_coupon.source
     *
     * @mbggenerated
     */
    public String getSource() {
        return source;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hq_coupon.source
     *
     * @param source the value for hq_coupon.source
     *
     * @mbggenerated
     */
    public void setSource(String source) {
        this.source = source == null ? null : source.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hq_coupon.status
     *
     * @return the value of hq_coupon.status
     *
     * @mbggenerated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hq_coupon.status
     *
     * @param status the value for hq_coupon.status
     *
     * @mbggenerated
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hq_coupon.admin_name
     *
     * @return the value of hq_coupon.admin_name
     *
     * @mbggenerated
     */
    public String getAdminName() {
        return adminName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hq_coupon.admin_name
     *
     * @param adminName the value for hq_coupon.admin_name
     *
     * @mbggenerated
     */
    public void setAdminName(String adminName) {
        this.adminName = adminName == null ? null : adminName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hq_coupon
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", hqCouponId=").append(hqCouponId);
        sb.append(", userId=").append(userId);
        sb.append(", incDays=").append(incDays);
        sb.append(", incRates=").append(incRates);
        sb.append(", createTime=").append(createTime);
        sb.append(", expiredTime=").append(expiredTime);
        sb.append(", usedTime=").append(usedTime);
        sb.append(", source=").append(source);
        sb.append(", status=").append(status);
        sb.append(", adminName=").append(adminName);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hq_coupon
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        HqCoupon other = (HqCoupon) that;
        return (this.getHqCouponId() == null ? other.getHqCouponId() == null : this.getHqCouponId().equals(other.getHqCouponId()))
            && (this.getUserId() == null ? other.getUserId() == null : this.getUserId().equals(other.getUserId()))
            && (this.getIncDays() == null ? other.getIncDays() == null : this.getIncDays().equals(other.getIncDays()))
            && (this.getIncRates() == null ? other.getIncRates() == null : this.getIncRates().equals(other.getIncRates()))
            && (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime().equals(other.getCreateTime()))
            && (this.getExpiredTime() == null ? other.getExpiredTime() == null : this.getExpiredTime().equals(other.getExpiredTime()))
            && (this.getUsedTime() == null ? other.getUsedTime() == null : this.getUsedTime().equals(other.getUsedTime()))
            && (this.getSource() == null ? other.getSource() == null : this.getSource().equals(other.getSource()))
            && (this.getStatus() == null ? other.getStatus() == null : this.getStatus().equals(other.getStatus()))
            && (this.getAdminName() == null ? other.getAdminName() == null : this.getAdminName().equals(other.getAdminName()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hq_coupon
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getHqCouponId() == null) ? 0 : getHqCouponId().hashCode());
        result = prime * result + ((getUserId() == null) ? 0 : getUserId().hashCode());
        result = prime * result + ((getIncDays() == null) ? 0 : getIncDays().hashCode());
        result = prime * result + ((getIncRates() == null) ? 0 : getIncRates().hashCode());
        result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
        result = prime * result + ((getExpiredTime() == null) ? 0 : getExpiredTime().hashCode());
        result = prime * result + ((getUsedTime() == null) ? 0 : getUsedTime().hashCode());
        result = prime * result + ((getSource() == null) ? 0 : getSource().hashCode());
        result = prime * result + ((getStatus() == null) ? 0 : getStatus().hashCode());
        result = prime * result + ((getAdminName() == null) ? 0 : getAdminName().hashCode());
        return result;
    }
}