package com.p2g.mybatis.model.generator;

import java.io.Serializable;
import java.util.Date;

public class Users implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.user_id
     *
     * @mbggenerated
     */
    private Long userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.mobile
     *
     * @mbggenerated
     */
    private String mobile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.weixin
     *
     * @mbggenerated
     */
    private String weixin;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.union_id
     *
     * @mbggenerated
     */
    private String unionId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.weixin_bind_time
     *
     * @mbggenerated
     */
    private Date weixinBindTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.login_password
     *
     * @mbggenerated
     */
    private String loginPassword;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.login_password_salt
     *
     * @mbggenerated
     */
    private String loginPasswordSalt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.his_invite_code
     *
     * @mbggenerated
     */
    private String hisInviteCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.invite_user_id
     *
     * @mbggenerated
     */
    private Long inviteUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.invite_mode
     *
     * @mbggenerated
     */
    private String inviteMode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.reg_invite_code
     *
     * @mbggenerated
     */
    private String regInviteCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.user_name
     *
     * @mbggenerated
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.id_card
     *
     * @mbggenerated
     */
    private String idCard;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.is_idcheck
     *
     * @mbggenerated
     */
    private String isIdcheck;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.status
     *
     * @mbggenerated
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.reg_time
     *
     * @mbggenerated
     */
    private Date regTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.device_source
     *
     * @mbggenerated
     */
    private String deviceSource;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.invite_right
     *
     * @mbggenerated
     */
    private String inviteRight;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.inside_invite_right
     *
     * @mbggenerated
     */
    private String insideInviteRight;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.nick_name
     *
     * @mbggenerated
     */
    private String nickName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.head_img_url
     *
     * @mbggenerated
     */
    private String headImgUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table users
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.user_id
     *
     * @return the value of users.user_id
     *
     * @mbggenerated
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.user_id
     *
     * @param userId the value for users.user_id
     *
     * @mbggenerated
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.mobile
     *
     * @return the value of users.mobile
     *
     * @mbggenerated
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.mobile
     *
     * @param mobile the value for users.mobile
     *
     * @mbggenerated
     */
    public void setMobile(String mobile) {
        this.mobile = mobile == null ? null : mobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.weixin
     *
     * @return the value of users.weixin
     *
     * @mbggenerated
     */
    public String getWeixin() {
        return weixin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.weixin
     *
     * @param weixin the value for users.weixin
     *
     * @mbggenerated
     */
    public void setWeixin(String weixin) {
        this.weixin = weixin == null ? null : weixin.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.union_id
     *
     * @return the value of users.union_id
     *
     * @mbggenerated
     */
    public String getUnionId() {
        return unionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.union_id
     *
     * @param unionId the value for users.union_id
     *
     * @mbggenerated
     */
    public void setUnionId(String unionId) {
        this.unionId = unionId == null ? null : unionId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.weixin_bind_time
     *
     * @return the value of users.weixin_bind_time
     *
     * @mbggenerated
     */
    public Date getWeixinBindTime() {
        return weixinBindTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.weixin_bind_time
     *
     * @param weixinBindTime the value for users.weixin_bind_time
     *
     * @mbggenerated
     */
    public void setWeixinBindTime(Date weixinBindTime) {
        this.weixinBindTime = weixinBindTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.login_password
     *
     * @return the value of users.login_password
     *
     * @mbggenerated
     */
    public String getLoginPassword() {
        return loginPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.login_password
     *
     * @param loginPassword the value for users.login_password
     *
     * @mbggenerated
     */
    public void setLoginPassword(String loginPassword) {
        this.loginPassword = loginPassword == null ? null : loginPassword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.login_password_salt
     *
     * @return the value of users.login_password_salt
     *
     * @mbggenerated
     */
    public String getLoginPasswordSalt() {
        return loginPasswordSalt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.login_password_salt
     *
     * @param loginPasswordSalt the value for users.login_password_salt
     *
     * @mbggenerated
     */
    public void setLoginPasswordSalt(String loginPasswordSalt) {
        this.loginPasswordSalt = loginPasswordSalt == null ? null : loginPasswordSalt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.his_invite_code
     *
     * @return the value of users.his_invite_code
     *
     * @mbggenerated
     */
    public String getHisInviteCode() {
        return hisInviteCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.his_invite_code
     *
     * @param hisInviteCode the value for users.his_invite_code
     *
     * @mbggenerated
     */
    public void setHisInviteCode(String hisInviteCode) {
        this.hisInviteCode = hisInviteCode == null ? null : hisInviteCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.invite_user_id
     *
     * @return the value of users.invite_user_id
     *
     * @mbggenerated
     */
    public Long getInviteUserId() {
        return inviteUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.invite_user_id
     *
     * @param inviteUserId the value for users.invite_user_id
     *
     * @mbggenerated
     */
    public void setInviteUserId(Long inviteUserId) {
        this.inviteUserId = inviteUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.invite_mode
     *
     * @return the value of users.invite_mode
     *
     * @mbggenerated
     */
    public String getInviteMode() {
        return inviteMode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.invite_mode
     *
     * @param inviteMode the value for users.invite_mode
     *
     * @mbggenerated
     */
    public void setInviteMode(String inviteMode) {
        this.inviteMode = inviteMode == null ? null : inviteMode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.reg_invite_code
     *
     * @return the value of users.reg_invite_code
     *
     * @mbggenerated
     */
    public String getRegInviteCode() {
        return regInviteCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.reg_invite_code
     *
     * @param regInviteCode the value for users.reg_invite_code
     *
     * @mbggenerated
     */
    public void setRegInviteCode(String regInviteCode) {
        this.regInviteCode = regInviteCode == null ? null : regInviteCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.user_name
     *
     * @return the value of users.user_name
     *
     * @mbggenerated
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.user_name
     *
     * @param userName the value for users.user_name
     *
     * @mbggenerated
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.id_card
     *
     * @return the value of users.id_card
     *
     * @mbggenerated
     */
    public String getIdCard() {
        return idCard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.id_card
     *
     * @param idCard the value for users.id_card
     *
     * @mbggenerated
     */
    public void setIdCard(String idCard) {
        this.idCard = idCard == null ? null : idCard.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.is_idcheck
     *
     * @return the value of users.is_idcheck
     *
     * @mbggenerated
     */
    public String getIsIdcheck() {
        return isIdcheck;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.is_idcheck
     *
     * @param isIdcheck the value for users.is_idcheck
     *
     * @mbggenerated
     */
    public void setIsIdcheck(String isIdcheck) {
        this.isIdcheck = isIdcheck == null ? null : isIdcheck.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.status
     *
     * @return the value of users.status
     *
     * @mbggenerated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.status
     *
     * @param status the value for users.status
     *
     * @mbggenerated
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.reg_time
     *
     * @return the value of users.reg_time
     *
     * @mbggenerated
     */
    public Date getRegTime() {
        return regTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.reg_time
     *
     * @param regTime the value for users.reg_time
     *
     * @mbggenerated
     */
    public void setRegTime(Date regTime) {
        this.regTime = regTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.device_source
     *
     * @return the value of users.device_source
     *
     * @mbggenerated
     */
    public String getDeviceSource() {
        return deviceSource;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.device_source
     *
     * @param deviceSource the value for users.device_source
     *
     * @mbggenerated
     */
    public void setDeviceSource(String deviceSource) {
        this.deviceSource = deviceSource == null ? null : deviceSource.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.invite_right
     *
     * @return the value of users.invite_right
     *
     * @mbggenerated
     */
    public String getInviteRight() {
        return inviteRight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.invite_right
     *
     * @param inviteRight the value for users.invite_right
     *
     * @mbggenerated
     */
    public void setInviteRight(String inviteRight) {
        this.inviteRight = inviteRight == null ? null : inviteRight.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.inside_invite_right
     *
     * @return the value of users.inside_invite_right
     *
     * @mbggenerated
     */
    public String getInsideInviteRight() {
        return insideInviteRight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.inside_invite_right
     *
     * @param insideInviteRight the value for users.inside_invite_right
     *
     * @mbggenerated
     */
    public void setInsideInviteRight(String insideInviteRight) {
        this.insideInviteRight = insideInviteRight == null ? null : insideInviteRight.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.nick_name
     *
     * @return the value of users.nick_name
     *
     * @mbggenerated
     */
    public String getNickName() {
        return nickName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.nick_name
     *
     * @param nickName the value for users.nick_name
     *
     * @mbggenerated
     */
    public void setNickName(String nickName) {
        this.nickName = nickName == null ? null : nickName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.head_img_url
     *
     * @return the value of users.head_img_url
     *
     * @mbggenerated
     */
    public String getHeadImgUrl() {
        return headImgUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.head_img_url
     *
     * @param headImgUrl the value for users.head_img_url
     *
     * @mbggenerated
     */
    public void setHeadImgUrl(String headImgUrl) {
        this.headImgUrl = headImgUrl == null ? null : headImgUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", userId=").append(userId);
        sb.append(", mobile=").append(mobile);
        sb.append(", weixin=").append(weixin);
        sb.append(", unionId=").append(unionId);
        sb.append(", weixinBindTime=").append(weixinBindTime);
        sb.append(", loginPassword=").append(loginPassword);
        sb.append(", loginPasswordSalt=").append(loginPasswordSalt);
        sb.append(", hisInviteCode=").append(hisInviteCode);
        sb.append(", inviteUserId=").append(inviteUserId);
        sb.append(", inviteMode=").append(inviteMode);
        sb.append(", regInviteCode=").append(regInviteCode);
        sb.append(", userName=").append(userName);
        sb.append(", idCard=").append(idCard);
        sb.append(", isIdcheck=").append(isIdcheck);
        sb.append(", status=").append(status);
        sb.append(", regTime=").append(regTime);
        sb.append(", deviceSource=").append(deviceSource);
        sb.append(", inviteRight=").append(inviteRight);
        sb.append(", insideInviteRight=").append(insideInviteRight);
        sb.append(", nickName=").append(nickName);
        sb.append(", headImgUrl=").append(headImgUrl);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Users other = (Users) that;
        return (this.getUserId() == null ? other.getUserId() == null : this.getUserId().equals(other.getUserId()))
            && (this.getMobile() == null ? other.getMobile() == null : this.getMobile().equals(other.getMobile()))
            && (this.getWeixin() == null ? other.getWeixin() == null : this.getWeixin().equals(other.getWeixin()))
            && (this.getUnionId() == null ? other.getUnionId() == null : this.getUnionId().equals(other.getUnionId()))
            && (this.getWeixinBindTime() == null ? other.getWeixinBindTime() == null : this.getWeixinBindTime().equals(other.getWeixinBindTime()))
            && (this.getLoginPassword() == null ? other.getLoginPassword() == null : this.getLoginPassword().equals(other.getLoginPassword()))
            && (this.getLoginPasswordSalt() == null ? other.getLoginPasswordSalt() == null : this.getLoginPasswordSalt().equals(other.getLoginPasswordSalt()))
            && (this.getHisInviteCode() == null ? other.getHisInviteCode() == null : this.getHisInviteCode().equals(other.getHisInviteCode()))
            && (this.getInviteUserId() == null ? other.getInviteUserId() == null : this.getInviteUserId().equals(other.getInviteUserId()))
            && (this.getInviteMode() == null ? other.getInviteMode() == null : this.getInviteMode().equals(other.getInviteMode()))
            && (this.getRegInviteCode() == null ? other.getRegInviteCode() == null : this.getRegInviteCode().equals(other.getRegInviteCode()))
            && (this.getUserName() == null ? other.getUserName() == null : this.getUserName().equals(other.getUserName()))
            && (this.getIdCard() == null ? other.getIdCard() == null : this.getIdCard().equals(other.getIdCard()))
            && (this.getIsIdcheck() == null ? other.getIsIdcheck() == null : this.getIsIdcheck().equals(other.getIsIdcheck()))
            && (this.getStatus() == null ? other.getStatus() == null : this.getStatus().equals(other.getStatus()))
            && (this.getRegTime() == null ? other.getRegTime() == null : this.getRegTime().equals(other.getRegTime()))
            && (this.getDeviceSource() == null ? other.getDeviceSource() == null : this.getDeviceSource().equals(other.getDeviceSource()))
            && (this.getInviteRight() == null ? other.getInviteRight() == null : this.getInviteRight().equals(other.getInviteRight()))
            && (this.getInsideInviteRight() == null ? other.getInsideInviteRight() == null : this.getInsideInviteRight().equals(other.getInsideInviteRight()))
            && (this.getNickName() == null ? other.getNickName() == null : this.getNickName().equals(other.getNickName()))
            && (this.getHeadImgUrl() == null ? other.getHeadImgUrl() == null : this.getHeadImgUrl().equals(other.getHeadImgUrl()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getUserId() == null) ? 0 : getUserId().hashCode());
        result = prime * result + ((getMobile() == null) ? 0 : getMobile().hashCode());
        result = prime * result + ((getWeixin() == null) ? 0 : getWeixin().hashCode());
        result = prime * result + ((getUnionId() == null) ? 0 : getUnionId().hashCode());
        result = prime * result + ((getWeixinBindTime() == null) ? 0 : getWeixinBindTime().hashCode());
        result = prime * result + ((getLoginPassword() == null) ? 0 : getLoginPassword().hashCode());
        result = prime * result + ((getLoginPasswordSalt() == null) ? 0 : getLoginPasswordSalt().hashCode());
        result = prime * result + ((getHisInviteCode() == null) ? 0 : getHisInviteCode().hashCode());
        result = prime * result + ((getInviteUserId() == null) ? 0 : getInviteUserId().hashCode());
        result = prime * result + ((getInviteMode() == null) ? 0 : getInviteMode().hashCode());
        result = prime * result + ((getRegInviteCode() == null) ? 0 : getRegInviteCode().hashCode());
        result = prime * result + ((getUserName() == null) ? 0 : getUserName().hashCode());
        result = prime * result + ((getIdCard() == null) ? 0 : getIdCard().hashCode());
        result = prime * result + ((getIsIdcheck() == null) ? 0 : getIsIdcheck().hashCode());
        result = prime * result + ((getStatus() == null) ? 0 : getStatus().hashCode());
        result = prime * result + ((getRegTime() == null) ? 0 : getRegTime().hashCode());
        result = prime * result + ((getDeviceSource() == null) ? 0 : getDeviceSource().hashCode());
        result = prime * result + ((getInviteRight() == null) ? 0 : getInviteRight().hashCode());
        result = prime * result + ((getInsideInviteRight() == null) ? 0 : getInsideInviteRight().hashCode());
        result = prime * result + ((getNickName() == null) ? 0 : getNickName().hashCode());
        result = prime * result + ((getHeadImgUrl() == null) ? 0 : getHeadImgUrl().hashCode());
        return result;
    }
}