package com.shop.mybatis.dao.sys;

import com.shop.mybatis.model.generator.InviteAuthorityCode;
import java.util.List;

public interface InviteAuthorityCodeExpandMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table invite_authority_code
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String inviteCode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table invite_authority_code
     *
     * @mbggenerated
     */
    int insert(InviteAuthorityCode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table invite_authority_code
     *
     * @mbggenerated
     */
    InviteAuthorityCode selectByPrimaryKey(String inviteCode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table invite_authority_code
     *
     * @mbggenerated
     */
    List<InviteAuthorityCode> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table invite_authority_code
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(InviteAuthorityCode record);

	void updateByPrimaryKeySelective(InviteAuthorityCode code2);
}