package com.shop.mybatis.model.generator;

import java.io.Serializable;
import java.util.Date;

public class OrderformRecord implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderform_record.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderform_record.user_id
     *
     * @mbggenerated
     */
    private Long userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderform_record.phone
     *
     * @mbggenerated
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderform_record.number
     *
     * @mbggenerated
     */
    private String number;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderform_record.express
     *
     * @mbggenerated
     */
    private String express;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderform_record.addresser
     *
     * @mbggenerated
     */
    private String addresser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderform_record.addressee
     *
     * @mbggenerated
     */
    private String addressee;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderform_record.merchandise
     *
     * @mbggenerated
     */
    private String merchandise;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderform_record.shopping_address
     *
     * @mbggenerated
     */
    private String shoppingAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderform_record.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table orderform_record
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderform_record.id
     *
     * @return the value of orderform_record.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderform_record.id
     *
     * @param id the value for orderform_record.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderform_record.user_id
     *
     * @return the value of orderform_record.user_id
     *
     * @mbggenerated
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderform_record.user_id
     *
     * @param userId the value for orderform_record.user_id
     *
     * @mbggenerated
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderform_record.phone
     *
     * @return the value of orderform_record.phone
     *
     * @mbggenerated
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderform_record.phone
     *
     * @param phone the value for orderform_record.phone
     *
     * @mbggenerated
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderform_record.number
     *
     * @return the value of orderform_record.number
     *
     * @mbggenerated
     */
    public String getNumber() {
        return number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderform_record.number
     *
     * @param number the value for orderform_record.number
     *
     * @mbggenerated
     */
    public void setNumber(String number) {
        this.number = number == null ? null : number.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderform_record.express
     *
     * @return the value of orderform_record.express
     *
     * @mbggenerated
     */
    public String getExpress() {
        return express;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderform_record.express
     *
     * @param express the value for orderform_record.express
     *
     * @mbggenerated
     */
    public void setExpress(String express) {
        this.express = express == null ? null : express.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderform_record.addresser
     *
     * @return the value of orderform_record.addresser
     *
     * @mbggenerated
     */
    public String getAddresser() {
        return addresser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderform_record.addresser
     *
     * @param addresser the value for orderform_record.addresser
     *
     * @mbggenerated
     */
    public void setAddresser(String addresser) {
        this.addresser = addresser == null ? null : addresser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderform_record.addressee
     *
     * @return the value of orderform_record.addressee
     *
     * @mbggenerated
     */
    public String getAddressee() {
        return addressee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderform_record.addressee
     *
     * @param addressee the value for orderform_record.addressee
     *
     * @mbggenerated
     */
    public void setAddressee(String addressee) {
        this.addressee = addressee == null ? null : addressee.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderform_record.merchandise
     *
     * @return the value of orderform_record.merchandise
     *
     * @mbggenerated
     */
    public String getMerchandise() {
        return merchandise;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderform_record.merchandise
     *
     * @param merchandise the value for orderform_record.merchandise
     *
     * @mbggenerated
     */
    public void setMerchandise(String merchandise) {
        this.merchandise = merchandise == null ? null : merchandise.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderform_record.shopping_address
     *
     * @return the value of orderform_record.shopping_address
     *
     * @mbggenerated
     */
    public String getShoppingAddress() {
        return shoppingAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderform_record.shopping_address
     *
     * @param shoppingAddress the value for orderform_record.shopping_address
     *
     * @mbggenerated
     */
    public void setShoppingAddress(String shoppingAddress) {
        this.shoppingAddress = shoppingAddress == null ? null : shoppingAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderform_record.create_time
     *
     * @return the value of orderform_record.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderform_record.create_time
     *
     * @param createTime the value for orderform_record.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderform_record
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", userId=").append(userId);
        sb.append(", phone=").append(phone);
        sb.append(", number=").append(number);
        sb.append(", express=").append(express);
        sb.append(", addresser=").append(addresser);
        sb.append(", addressee=").append(addressee);
        sb.append(", merchandise=").append(merchandise);
        sb.append(", shoppingAddress=").append(shoppingAddress);
        sb.append(", createTime=").append(createTime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderform_record
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        OrderformRecord other = (OrderformRecord) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getUserId() == null ? other.getUserId() == null : this.getUserId().equals(other.getUserId()))
            && (this.getPhone() == null ? other.getPhone() == null : this.getPhone().equals(other.getPhone()))
            && (this.getNumber() == null ? other.getNumber() == null : this.getNumber().equals(other.getNumber()))
            && (this.getExpress() == null ? other.getExpress() == null : this.getExpress().equals(other.getExpress()))
            && (this.getAddresser() == null ? other.getAddresser() == null : this.getAddresser().equals(other.getAddresser()))
            && (this.getAddressee() == null ? other.getAddressee() == null : this.getAddressee().equals(other.getAddressee()))
            && (this.getMerchandise() == null ? other.getMerchandise() == null : this.getMerchandise().equals(other.getMerchandise()))
            && (this.getShoppingAddress() == null ? other.getShoppingAddress() == null : this.getShoppingAddress().equals(other.getShoppingAddress()))
            && (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime().equals(other.getCreateTime()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderform_record
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getUserId() == null) ? 0 : getUserId().hashCode());
        result = prime * result + ((getPhone() == null) ? 0 : getPhone().hashCode());
        result = prime * result + ((getNumber() == null) ? 0 : getNumber().hashCode());
        result = prime * result + ((getExpress() == null) ? 0 : getExpress().hashCode());
        result = prime * result + ((getAddresser() == null) ? 0 : getAddresser().hashCode());
        result = prime * result + ((getAddressee() == null) ? 0 : getAddressee().hashCode());
        result = prime * result + ((getMerchandise() == null) ? 0 : getMerchandise().hashCode());
        result = prime * result + ((getShoppingAddress() == null) ? 0 : getShoppingAddress().hashCode());
        result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
        return result;
    }
}