package com.shop.mybatis.model.generator;

import java.io.Serializable;
import java.util.Date;

public class Users implements Serializable{
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.user_id
     *
     * @mbggenerated Wed May 23 14:06:49 CST 2018
     */
    private Long userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.mobile
     *
     * @mbggenerated Wed May 23 14:06:49 CST 2018
     */
    private String mobile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.weixin
     *
     * @mbggenerated Wed May 23 14:06:49 CST 2018
     */
    private String weixin;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.union_id
     *
     * @mbggenerated Wed May 23 14:06:49 CST 2018
     */
    private String unionId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.weixin_bind_time
     *
     * @mbggenerated Wed May 23 14:06:49 CST 2018
     */
    private Date weixinBindTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.login_password
     *
     * @mbggenerated Wed May 23 14:06:49 CST 2018
     */
    private String loginPassword;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.login_password_salt
     *
     * @mbggenerated Wed May 23 14:06:49 CST 2018
     */
    private String loginPasswordSalt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.his_invite_code
     *
     * @mbggenerated Wed May 23 14:06:49 CST 2018
     */
    private String hisInviteCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.invite_user_id
     *
     * @mbggenerated Wed May 23 14:06:49 CST 2018
     */
    private Long inviteUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.invite_mode
     *
     * @mbggenerated Wed May 23 14:06:49 CST 2018
     */
    private String inviteMode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.reg_invite_code
     *
     * @mbggenerated Wed May 23 14:06:49 CST 2018
     */
    private String regInviteCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.user_name
     *
     * @mbggenerated Wed May 23 14:06:49 CST 2018
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.id_card
     *
     * @mbggenerated Wed May 23 14:06:49 CST 2018
     */
    private String idCard;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.is_idcheck
     *
     * @mbggenerated Wed May 23 14:06:49 CST 2018
     */
    private String isIdcheck;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.status
     *
     * @mbggenerated Wed May 23 14:06:49 CST 2018
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.reg_time
     *
     * @mbggenerated Wed May 23 14:06:49 CST 2018
     */
    private Date regTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.device_source
     *
     * @mbggenerated Wed May 23 14:06:49 CST 2018
     */
    private String deviceSource;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.invite_right
     *
     * @mbggenerated Wed May 23 14:06:49 CST 2018
     */
    private String inviteRight;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.inside_invite_right
     *
     * @mbggenerated Wed May 23 14:06:49 CST 2018
     */
    private String insideInviteRight;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.nick_name
     *
     * @mbggenerated Wed May 23 14:06:49 CST 2018
     */
    private String nickName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.head_img_url
     *
     * @mbggenerated Wed May 23 14:06:49 CST 2018
     */
    private String headImgUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.business_invite_code
     *
     * @mbggenerated Wed May 23 14:06:49 CST 2018
     */
    private String businessInviteCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.is_jajr
     *
     * @mbggenerated Wed May 23 14:06:49 CST 2018
     */
    private String isJajr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.ip
     *
     * @mbggenerated Wed May 23 14:06:49 CST 2018
     */
    private String ip;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.email
     *
     * @mbggenerated Wed May 23 14:06:49 CST 2018
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.wx_Name
     *
     * @mbggenerated Wed May 23 14:06:49 CST 2018
     */
    private String wxName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.qq
     *
     * @mbggenerated Wed May 23 14:06:49 CST 2018
     */
    private String qq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.superior_Id
     *
     * @mbggenerated Wed May 23 14:06:49 CST 2018
     */
    private Long superiorId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.subordinate_Id
     *
     * @mbggenerated Wed May 23 14:06:49 CST 2018
     */
    private Long subordinateId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.add_Friend
     *
     * @mbggenerated Wed May 23 14:06:49 CST 2018
     */
    private String addFriend;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.become_Agent
     *
     * @mbggenerated Wed May 23 14:06:49 CST 2018
     */
    private String becomeAgent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.count
     *
     * @mbggenerated Wed May 23 14:06:49 CST 2018
     */
    private Integer count;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.jurisdiction
     *
     * @mbggenerated Wed May 23 14:06:49 CST 2018
     */
    private String jurisdiction;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.to_Examine
     *
     * @mbggenerated Wed May 23 14:06:49 CST 2018
     */
    private String toExamine;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.address
     *
     * @mbggenerated Wed May 23 14:06:49 CST 2018
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.top_Level
     *
     * @mbggenerated Wed May 23 14:06:49 CST 2018
     */
    private Long topLevel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.invite_person_num
     *
     * @mbggenerated Wed May 23 14:06:49 CST 2018
     */
    private Integer invitePersonNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.create_Time
     *
     * @mbggenerated Wed May 23 14:06:49 CST 2018
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.update_Time
     *
     * @mbggenerated Wed May 23 14:06:49 CST 2018
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.superior_agent_id
     *
     * @mbggenerated Wed May 23 14:06:49 CST 2018
     */
    private Long superiorAgentId;
    private String userType;//非数据库字段 0普通用户  1顶级代理商
    public String getUserType() {
		return userType;
	}

	public void setUserType(String userType) {
		this.userType = userType;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.user_id
     *
     * @return the value of users.user_id
     *
     * @mbggenerated Wed May 23 14:06:49 CST 2018
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.user_id
     *
     * @param userId the value for users.user_id
     *
     * @mbggenerated Wed May 23 14:06:49 CST 2018
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.mobile
     *
     * @return the value of users.mobile
     *
     * @mbggenerated Wed May 23 14:06:49 CST 2018
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.mobile
     *
     * @param mobile the value for users.mobile
     *
     * @mbggenerated Wed May 23 14:06:49 CST 2018
     */
    public void setMobile(String mobile) {
        this.mobile = mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.weixin
     *
     * @return the value of users.weixin
     *
     * @mbggenerated Wed May 23 14:06:49 CST 2018
     */
    public String getWeixin() {
        return weixin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.weixin
     *
     * @param weixin the value for users.weixin
     *
     * @mbggenerated Wed May 23 14:06:49 CST 2018
     */
    public void setWeixin(String weixin) {
        this.weixin = weixin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.union_id
     *
     * @return the value of users.union_id
     *
     * @mbggenerated Wed May 23 14:06:49 CST 2018
     */
    public String getUnionId() {
        return unionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.union_id
     *
     * @param unionId the value for users.union_id
     *
     * @mbggenerated Wed May 23 14:06:49 CST 2018
     */
    public void setUnionId(String unionId) {
        this.unionId = unionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.weixin_bind_time
     *
     * @return the value of users.weixin_bind_time
     *
     * @mbggenerated Wed May 23 14:06:49 CST 2018
     */
    public Date getWeixinBindTime() {
        return weixinBindTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.weixin_bind_time
     *
     * @param weixinBindTime the value for users.weixin_bind_time
     *
     * @mbggenerated Wed May 23 14:06:49 CST 2018
     */
    public void setWeixinBindTime(Date weixinBindTime) {
        this.weixinBindTime = weixinBindTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.login_password
     *
     * @return the value of users.login_password
     *
     * @mbggenerated Wed May 23 14:06:49 CST 2018
     */
    public String getLoginPassword() {
        return loginPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.login_password
     *
     * @param loginPassword the value for users.login_password
     *
     * @mbggenerated Wed May 23 14:06:49 CST 2018
     */
    public void setLoginPassword(String loginPassword) {
        this.loginPassword = loginPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.login_password_salt
     *
     * @return the value of users.login_password_salt
     *
     * @mbggenerated Wed May 23 14:06:49 CST 2018
     */
    public String getLoginPasswordSalt() {
        return loginPasswordSalt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.login_password_salt
     *
     * @param loginPasswordSalt the value for users.login_password_salt
     *
     * @mbggenerated Wed May 23 14:06:49 CST 2018
     */
    public void setLoginPasswordSalt(String loginPasswordSalt) {
        this.loginPasswordSalt = loginPasswordSalt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.his_invite_code
     *
     * @return the value of users.his_invite_code
     *
     * @mbggenerated Wed May 23 14:06:49 CST 2018
     */
    public String getHisInviteCode() {
        return hisInviteCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.his_invite_code
     *
     * @param hisInviteCode the value for users.his_invite_code
     *
     * @mbggenerated Wed May 23 14:06:49 CST 2018
     */
    public void setHisInviteCode(String hisInviteCode) {
        this.hisInviteCode = hisInviteCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.invite_user_id
     *
     * @return the value of users.invite_user_id
     *
     * @mbggenerated Wed May 23 14:06:49 CST 2018
     */
    public Long getInviteUserId() {
        return inviteUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.invite_user_id
     *
     * @param inviteUserId the value for users.invite_user_id
     *
     * @mbggenerated Wed May 23 14:06:49 CST 2018
     */
    public void setInviteUserId(Long inviteUserId) {
        this.inviteUserId = inviteUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.invite_mode
     *
     * @return the value of users.invite_mode
     *
     * @mbggenerated Wed May 23 14:06:49 CST 2018
     */
    public String getInviteMode() {
        return inviteMode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.invite_mode
     *
     * @param inviteMode the value for users.invite_mode
     *
     * @mbggenerated Wed May 23 14:06:49 CST 2018
     */
    public void setInviteMode(String inviteMode) {
        this.inviteMode = inviteMode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.reg_invite_code
     *
     * @return the value of users.reg_invite_code
     *
     * @mbggenerated Wed May 23 14:06:49 CST 2018
     */
    public String getRegInviteCode() {
        return regInviteCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.reg_invite_code
     *
     * @param regInviteCode the value for users.reg_invite_code
     *
     * @mbggenerated Wed May 23 14:06:49 CST 2018
     */
    public void setRegInviteCode(String regInviteCode) {
        this.regInviteCode = regInviteCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.user_name
     *
     * @return the value of users.user_name
     *
     * @mbggenerated Wed May 23 14:06:49 CST 2018
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.user_name
     *
     * @param userName the value for users.user_name
     *
     * @mbggenerated Wed May 23 14:06:49 CST 2018
     */
    public void setUserName(String userName) {
        this.userName = userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.id_card
     *
     * @return the value of users.id_card
     *
     * @mbggenerated Wed May 23 14:06:49 CST 2018
     */
    public String getIdCard() {
        return idCard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.id_card
     *
     * @param idCard the value for users.id_card
     *
     * @mbggenerated Wed May 23 14:06:49 CST 2018
     */
    public void setIdCard(String idCard) {
        this.idCard = idCard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.is_idcheck
     *
     * @return the value of users.is_idcheck
     *
     * @mbggenerated Wed May 23 14:06:49 CST 2018
     */
    public String getIsIdcheck() {
        return isIdcheck;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.is_idcheck
     *
     * @param isIdcheck the value for users.is_idcheck
     *
     * @mbggenerated Wed May 23 14:06:49 CST 2018
     */
    public void setIsIdcheck(String isIdcheck) {
        this.isIdcheck = isIdcheck;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.status
     *
     * @return the value of users.status
     *
     * @mbggenerated Wed May 23 14:06:49 CST 2018
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.status
     *
     * @param status the value for users.status
     *
     * @mbggenerated Wed May 23 14:06:49 CST 2018
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.reg_time
     *
     * @return the value of users.reg_time
     *
     * @mbggenerated Wed May 23 14:06:49 CST 2018
     */
    public Date getRegTime() {
        return regTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.reg_time
     *
     * @param regTime the value for users.reg_time
     *
     * @mbggenerated Wed May 23 14:06:49 CST 2018
     */
    public void setRegTime(Date regTime) {
        this.regTime = regTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.device_source
     *
     * @return the value of users.device_source
     *
     * @mbggenerated Wed May 23 14:06:49 CST 2018
     */
    public String getDeviceSource() {
        return deviceSource;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.device_source
     *
     * @param deviceSource the value for users.device_source
     *
     * @mbggenerated Wed May 23 14:06:49 CST 2018
     */
    public void setDeviceSource(String deviceSource) {
        this.deviceSource = deviceSource;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.invite_right
     *
     * @return the value of users.invite_right
     *
     * @mbggenerated Wed May 23 14:06:49 CST 2018
     */
    public String getInviteRight() {
        return inviteRight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.invite_right
     *
     * @param inviteRight the value for users.invite_right
     *
     * @mbggenerated Wed May 23 14:06:49 CST 2018
     */
    public void setInviteRight(String inviteRight) {
        this.inviteRight = inviteRight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.inside_invite_right
     *
     * @return the value of users.inside_invite_right
     *
     * @mbggenerated Wed May 23 14:06:49 CST 2018
     */
    public String getInsideInviteRight() {
        return insideInviteRight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.inside_invite_right
     *
     * @param insideInviteRight the value for users.inside_invite_right
     *
     * @mbggenerated Wed May 23 14:06:49 CST 2018
     */
    public void setInsideInviteRight(String insideInviteRight) {
        this.insideInviteRight = insideInviteRight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.nick_name
     *
     * @return the value of users.nick_name
     *
     * @mbggenerated Wed May 23 14:06:49 CST 2018
     */
    public String getNickName() {
        return nickName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.nick_name
     *
     * @param nickName the value for users.nick_name
     *
     * @mbggenerated Wed May 23 14:06:49 CST 2018
     */
    public void setNickName(String nickName) {
        this.nickName = nickName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.head_img_url
     *
     * @return the value of users.head_img_url
     *
     * @mbggenerated Wed May 23 14:06:49 CST 2018
     */
    public String getHeadImgUrl() {
        return headImgUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.head_img_url
     *
     * @param headImgUrl the value for users.head_img_url
     *
     * @mbggenerated Wed May 23 14:06:49 CST 2018
     */
    public void setHeadImgUrl(String headImgUrl) {
        this.headImgUrl = headImgUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.business_invite_code
     *
     * @return the value of users.business_invite_code
     *
     * @mbggenerated Wed May 23 14:06:49 CST 2018
     */
    public String getBusinessInviteCode() {
        return businessInviteCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.business_invite_code
     *
     * @param businessInviteCode the value for users.business_invite_code
     *
     * @mbggenerated Wed May 23 14:06:49 CST 2018
     */
    public void setBusinessInviteCode(String businessInviteCode) {
        this.businessInviteCode = businessInviteCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.is_jajr
     *
     * @return the value of users.is_jajr
     *
     * @mbggenerated Wed May 23 14:06:49 CST 2018
     */
    public String getIsJajr() {
        return isJajr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.is_jajr
     *
     * @param isJajr the value for users.is_jajr
     *
     * @mbggenerated Wed May 23 14:06:49 CST 2018
     */
    public void setIsJajr(String isJajr) {
        this.isJajr = isJajr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.ip
     *
     * @return the value of users.ip
     *
     * @mbggenerated Wed May 23 14:06:49 CST 2018
     */
    public String getIp() {
        return ip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.ip
     *
     * @param ip the value for users.ip
     *
     * @mbggenerated Wed May 23 14:06:49 CST 2018
     */
    public void setIp(String ip) {
        this.ip = ip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.email
     *
     * @return the value of users.email
     *
     * @mbggenerated Wed May 23 14:06:49 CST 2018
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.email
     *
     * @param email the value for users.email
     *
     * @mbggenerated Wed May 23 14:06:49 CST 2018
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.wx_Name
     *
     * @return the value of users.wx_Name
     *
     * @mbggenerated Wed May 23 14:06:49 CST 2018
     */
    public String getWxName() {
        return wxName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.wx_Name
     *
     * @param wxName the value for users.wx_Name
     *
     * @mbggenerated Wed May 23 14:06:49 CST 2018
     */
    public void setWxName(String wxName) {
        this.wxName = wxName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.qq
     *
     * @return the value of users.qq
     *
     * @mbggenerated Wed May 23 14:06:49 CST 2018
     */
    public String getQq() {
        return qq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.qq
     *
     * @param qq the value for users.qq
     *
     * @mbggenerated Wed May 23 14:06:49 CST 2018
     */
    public void setQq(String qq) {
        this.qq = qq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.superior_Id
     *
     * @return the value of users.superior_Id
     *
     * @mbggenerated Wed May 23 14:06:49 CST 2018
     */
    public Long getSuperiorId() {
        return superiorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.superior_Id
     *
     * @param superiorId the value for users.superior_Id
     *
     * @mbggenerated Wed May 23 14:06:49 CST 2018
     */
    public void setSuperiorId(Long superiorId) {
        this.superiorId = superiorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.subordinate_Id
     *
     * @return the value of users.subordinate_Id
     *
     * @mbggenerated Wed May 23 14:06:49 CST 2018
     */
    public Long getSubordinateId() {
        return subordinateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.subordinate_Id
     *
     * @param subordinateId the value for users.subordinate_Id
     *
     * @mbggenerated Wed May 23 14:06:49 CST 2018
     */
    public void setSubordinateId(Long subordinateId) {
        this.subordinateId = subordinateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.add_Friend
     *
     * @return the value of users.add_Friend
     *
     * @mbggenerated Wed May 23 14:06:49 CST 2018
     */
    public String getAddFriend() {
        return addFriend;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.add_Friend
     *
     * @param addFriend the value for users.add_Friend
     *
     * @mbggenerated Wed May 23 14:06:49 CST 2018
     */
    public void setAddFriend(String addFriend) {
        this.addFriend = addFriend;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.become_Agent
     *
     * @return the value of users.become_Agent
     *
     * @mbggenerated Wed May 23 14:06:49 CST 2018
     */
    public String getBecomeAgent() {
        return becomeAgent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.become_Agent
     *
     * @param becomeAgent the value for users.become_Agent
     *
     * @mbggenerated Wed May 23 14:06:49 CST 2018
     */
    public void setBecomeAgent(String becomeAgent) {
        this.becomeAgent = becomeAgent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.count
     *
     * @return the value of users.count
     *
     * @mbggenerated Wed May 23 14:06:49 CST 2018
     */
    public Integer getCount() {
        return count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.count
     *
     * @param count the value for users.count
     *
     * @mbggenerated Wed May 23 14:06:49 CST 2018
     */
    public void setCount(Integer count) {
        this.count = count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.jurisdiction
     *
     * @return the value of users.jurisdiction
     *
     * @mbggenerated Wed May 23 14:06:49 CST 2018
     */
    public String getJurisdiction() {
        return jurisdiction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.jurisdiction
     *
     * @param jurisdiction the value for users.jurisdiction
     *
     * @mbggenerated Wed May 23 14:06:49 CST 2018
     */
    public void setJurisdiction(String jurisdiction) {
        this.jurisdiction = jurisdiction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.to_Examine
     *
     * @return the value of users.to_Examine
     *
     * @mbggenerated Wed May 23 14:06:49 CST 2018
     */
    public String getToExamine() {
        return toExamine;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.to_Examine
     *
     * @param toExamine the value for users.to_Examine
     *
     * @mbggenerated Wed May 23 14:06:49 CST 2018
     */
    public void setToExamine(String toExamine) {
        this.toExamine = toExamine;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.address
     *
     * @return the value of users.address
     *
     * @mbggenerated Wed May 23 14:06:49 CST 2018
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.address
     *
     * @param address the value for users.address
     *
     * @mbggenerated Wed May 23 14:06:49 CST 2018
     */
    public void setAddress(String address) {
        this.address = address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.top_Level
     *
     * @return the value of users.top_Level
     *
     * @mbggenerated Wed May 23 14:06:49 CST 2018
     */
    public Long getTopLevel() {
        return topLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.top_Level
     *
     * @param topLevel the value for users.top_Level
     *
     * @mbggenerated Wed May 23 14:06:49 CST 2018
     */
    public void setTopLevel(Long topLevel) {
        this.topLevel = topLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.invite_person_num
     *
     * @return the value of users.invite_person_num
     *
     * @mbggenerated Wed May 23 14:06:49 CST 2018
     */
    public Integer getInvitePersonNum() {
        return invitePersonNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.invite_person_num
     *
     * @param invitePersonNum the value for users.invite_person_num
     *
     * @mbggenerated Wed May 23 14:06:49 CST 2018
     */
    public void setInvitePersonNum(Integer invitePersonNum) {
        this.invitePersonNum = invitePersonNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.create_Time
     *
     * @return the value of users.create_Time
     *
     * @mbggenerated Wed May 23 14:06:49 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.create_Time
     *
     * @param createTime the value for users.create_Time
     *
     * @mbggenerated Wed May 23 14:06:49 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.update_Time
     *
     * @return the value of users.update_Time
     *
     * @mbggenerated Wed May 23 14:06:49 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.update_Time
     *
     * @param updateTime the value for users.update_Time
     *
     * @mbggenerated Wed May 23 14:06:49 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.superior_agent_id
     *
     * @return the value of users.superior_agent_id
     *
     * @mbggenerated Wed May 23 14:06:49 CST 2018
     */
    public Long getSuperiorAgentId() {
        return superiorAgentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.superior_agent_id
     *
     * @param superiorAgentId the value for users.superior_agent_id
     *
     * @mbggenerated Wed May 23 14:06:49 CST 2018
     */
    public void setSuperiorAgentId(Long superiorAgentId) {
        this.superiorAgentId = superiorAgentId;
    }
}