package com.p2g.mybatis.dao.generator;

import com.p2g.mybatis.model.generator.AdminUserMenu;
import java.util.List;

public interface AdminUserMenuMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_user_menu
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer adminUserMenuId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_user_menu
     *
     * @mbggenerated
     */
    int insert(AdminUserMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_user_menu
     *
     * @mbggenerated
     */
    AdminUserMenu selectByPrimaryKey(Integer adminUserMenuId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_user_menu
     *
     * @mbggenerated
     */
    List<AdminUserMenu> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_user_menu
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(AdminUserMenu record);
}