package com.p2g.mybatis.dao.generator;

import com.p2g.mybatis.model.generator.AdminDoLog;
import java.util.List;

public interface AdminDoLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_do_log
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long adminDoLogId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_do_log
     *
     * @mbggenerated
     */
    int insert(AdminDoLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_do_log
     *
     * @mbggenerated
     */
    AdminDoLog selectByPrimaryKey(Long adminDoLogId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_do_log
     *
     * @mbggenerated
     */
    List<AdminDoLog> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_do_log
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(AdminDoLog record);
}