package com.p2g.mybatis.dao.generator;

import com.p2g.mybatis.model.generator.AdminUserPermission;
import java.util.List;

public interface AdminUserPermissionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_user_permission
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer userPermissionId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_user_permission
     *
     * @mbggenerated
     */
    int insert(AdminUserPermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_user_permission
     *
     * @mbggenerated
     */
    AdminUserPermission selectByPrimaryKey(Integer userPermissionId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_user_permission
     *
     * @mbggenerated
     */
    List<AdminUserPermission> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_user_permission
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(AdminUserPermission record);
}