package com.p2g.mybatis.dao.generator;

import com.p2g.mybatis.model.generator.AdminRoleMenu;
import java.util.List;

public interface AdminRoleMenuMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_role_menu
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer adminRoleMenuId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_role_menu
     *
     * @mbggenerated
     */
    int insert(AdminRoleMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_role_menu
     *
     * @mbggenerated
     */
    AdminRoleMenu selectByPrimaryKey(Integer adminRoleMenuId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_role_menu
     *
     * @mbggenerated
     */
    List<AdminRoleMenu> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_role_menu
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(AdminRoleMenu record);
}