package com.p2g.mybatis.dao.generator;

import com.p2g.mybatis.model.generator.CmConfig;
import java.util.List;

public interface CmConfigMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cm_config
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer cmConfigId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cm_config
     *
     * @mbggenerated
     */
    int insert(CmConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cm_config
     *
     * @mbggenerated
     */
    CmConfig selectByPrimaryKey(Integer cmConfigId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cm_config
     *
     * @mbggenerated
     */
    List<CmConfig> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cm_config
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(CmConfig record);
}