package com.p2g.mybatis.dao.generator;

import com.p2g.mybatis.model.generator.CmSmsCode;
import java.util.List;

public interface CmSmsCodeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cm_sms_code
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long cmSmsCodeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cm_sms_code
     *
     * @mbggenerated
     */
    int insert(CmSmsCode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cm_sms_code
     *
     * @mbggenerated
     */
    CmSmsCode selectByPrimaryKey(Long cmSmsCodeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cm_sms_code
     *
     * @mbggenerated
     */
    List<CmSmsCode> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cm_sms_code
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(CmSmsCode record);
}