package com.p2g.mybatis.dao.generator;

import com.p2g.mybatis.model.generator.CmWeixinModel;
import java.util.List;

public interface CmWeixinModelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cm_weixin_model
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long cmWeixinModelId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cm_weixin_model
     *
     * @mbggenerated
     */
    int insert(CmWeixinModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cm_weixin_model
     *
     * @mbggenerated
     */
    CmWeixinModel selectByPrimaryKey(Long cmWeixinModelId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cm_weixin_model
     *
     * @mbggenerated
     */
    List<CmWeixinModel> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cm_weixin_model
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(CmWeixinModel record);
}