package com.p2g.mybatis.dao.generator;

import com.p2g.mybatis.model.generator.Coupons;
import java.util.List;

public interface CouponsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coupons
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long couponsId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coupons
     *
     * @mbggenerated
     */
    int insert(Coupons record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coupons
     *
     * @mbggenerated
     */
    Coupons selectByPrimaryKey(Long couponsId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coupons
     *
     * @mbggenerated
     */
    List<Coupons> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coupons
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Coupons record);
}