package com.p2g.mybatis.dao.generator;

import com.p2g.mybatis.model.generator.DqProduct;
import java.util.List;

public interface DqProductMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dq_product
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long dqProductId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dq_product
     *
     * @mbggenerated
     */
    int insert(DqProduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dq_product
     *
     * @mbggenerated
     */
    DqProduct selectByPrimaryKey(Long dqProductId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dq_product
     *
     * @mbggenerated
     */
    List<DqProduct> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dq_product
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(DqProduct record);
}