package com.p2g.mybatis.dao.generator;

import com.p2g.mybatis.model.generator.DqTransTmpLog;
import java.util.List;

public interface DqTransTmpLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dq_trans_tmp_log
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long dqTransTmpLogId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dq_trans_tmp_log
     *
     * @mbggenerated
     */
    int insert(DqTransTmpLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dq_trans_tmp_log
     *
     * @mbggenerated
     */
    DqTransTmpLog selectByPrimaryKey(Long dqTransTmpLogId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dq_trans_tmp_log
     *
     * @mbggenerated
     */
    List<DqTransTmpLog> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dq_trans_tmp_log
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(DqTransTmpLog record);
}