package com.p2g.mybatis.dao.generator;

import com.p2g.mybatis.model.generator.HqTransLog;
import java.util.List;

public interface HqTransLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hq_trans_log
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long hqTransLogId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hq_trans_log
     *
     * @mbggenerated
     */
    int insert(HqTransLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hq_trans_log
     *
     * @mbggenerated
     */
    HqTransLog selectByPrimaryKey(Long hqTransLogId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hq_trans_log
     *
     * @mbggenerated
     */
    List<HqTransLog> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hq_trans_log
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(HqTransLog record);
}