package com.p2g.mybatis.dao.generator;

import com.p2g.mybatis.model.generator.HqWithdrawCheck;
import java.util.List;

public interface HqWithdrawCheckMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hq_withdraw_check
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long hqWithdrawCheckId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hq_withdraw_check
     *
     * @mbggenerated
     */
    int insert(HqWithdrawCheck record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hq_withdraw_check
     *
     * @mbggenerated
     */
    HqWithdrawCheck selectByPrimaryKey(Long hqWithdrawCheckId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hq_withdraw_check
     *
     * @mbggenerated
     */
    List<HqWithdrawCheck> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hq_withdraw_check
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(HqWithdrawCheck record);
}