package com.p2g.mybatis.dao.generator;

import com.p2g.mybatis.model.generator.LianRechargeLog;
import java.util.List;

public interface LianRechargeLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lian_recharge_log
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long lianRechargeLogId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lian_recharge_log
     *
     * @mbggenerated
     */
    int insert(LianRechargeLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lian_recharge_log
     *
     * @mbggenerated
     */
    LianRechargeLog selectByPrimaryKey(Long lianRechargeLogId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lian_recharge_log
     *
     * @mbggenerated
     */
    List<LianRechargeLog> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lian_recharge_log
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(LianRechargeLog record);
}